### ISSUE TITLE
Ask for keychain access

### ISSUE THREAD

**Issue by lopezvit** [microsoft/vscode-mssql#17091] opened 2021-11-03 11:57 UTC
Issue Type: <b>Bug</b>

Related to https://github.com/microsoft/vscode/issues/136302

Extension version: 1.11.0
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|.git/config --crash-reporter-id 596370d3-e652-413b-8d2e-1652f767b25e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by mhtonysantaferra** [comment] 2021-11-03 15:47
I just ran into this today and it happens every time I open a new window.

**Comment by kburtram** [comment] 2021-11-03 16:40
@cssuh can you take a look at what is happening here?  We shouldn't be accessing the keychain unless the user is trying to establish a connection that requires reading a saved password.  Is this a recent change or perhaps an interaction with a different extension?

**Comment by kburtram** [comment] 2021-11-03 17:58
I'm going to close this as a duplicate of https://github.com/microsoft/vscode-mssql/issues/17064 so we can consolidate the investigation.  Please add any additional related comments there.  Thanks!

**Closed by kburtram** 2021-11-03 17:58 UTC
