### ISSUE TITLE
MSSQL won't edit existing profile

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/vscode-mssql#706] opened 2017-02-17 16:49 UTC
- MSSQL Extension Version: 0.2.1
- VSCode Version: 1.10.0-insider
- OS Version: Windows 10 Pro Insider Preview Build 15007.rs_prerelease.170107-1846

Steps to Reproduce:

1. Manually create a profile not on the Setting JSON file with the proper credentials. Then create another connection profile in the Settings JSON file in the folder storing the SQL Script.  The SQL connect will display both profiles.

2. F1 | ms | select Manage Connection Profiles | select "Edit"
This will not show the list of all existing profiles. It will jump to the VS Code general Settings JSON where I have no profile. This should display my existing Profiles and allow me to edit them.

This is forcing me to use the "Remove" option so I can recreate the profile again. 
It's a little bit tedious.

See attached images.
![mssql_02_2017-02-17_11-15-22](https://cloud.githubusercontent.com/assets/19892435/23074549/13381df8-f507-11e6-95df-a280a0e5e22e.jpg)
![mssql_03_2017-02-17_11-15-22](https://cloud.githubusercontent.com/assets/19892435/23074556/18696ab6-f507-11e6-8bc5-b2c89c9af7f5.jpg)

**Comment by llali** [comment] 2017-02-17 19:44
@MaximoTrinidad The profiles that you manually create are stored in the workspace settings if you have a workspace. Which should be the case here because you opened a folder. So you should be able to see your profiles if you select "Wokspace settings" after you selected "Edit".

**Comment by MaximoTrinidad** [comment] 2017-02-17 20:24
Yes! I understand now the ones you create in your own workspace settings.  I'm saying about the one you manually create outside the workspace file.  These are the ones you create when you click "mssql Connect", then follow the prompts and these are not stored in the Workspace file.

![mssql_02_2017-02-17_11-15-22](https://cloud.githubusercontent.com/assets/19892435/23081948/2b8a1eec-f525-11e6-953c-67ebd6b7f846.jpg)

**Comment by llali** [comment] 2017-02-17 20:35
So the profiles that are created by the mssql extension are stored in the user settings. We could add a new feature to ask user for the target to store the profile to. But for now this is by design.

**Comment by MaximoTrinidad** [comment] 2017-02-17 20:36
I just realized!! I'm expecting (or misleaded), under "Manage Connection Profiles" when I select "Edit" to see a list of connection(s) to edit.  But, this is not true. 

So, the purpose of "Edit" is to open the Workspace setting to make the change but still doesn't get me to the connections profile list.  

I think this is misleading, and I understand is a work in progress. Still, it would be nice if I can make changes to connection(s) that has been created outside the workspace setting file.

:)

Thanks

**Comment by MaximoTrinidad** [comment] 2017-02-17 20:40
Thanks @llali 

Yes! That sound great! I know things will keep changing and improving.  
:)

**Comment by llali** [comment] 2017-02-17 20:48
Yes there are going to be changes in this area probably. We have this limitations that we don't know to edit the profile in workspace or user settings because the profile can be in either settings. I close this for now because it's by design. Thanks for your feedback!

**Closed by llali** 2017-02-17 20:48 UTC
Labels: bug, customer issue
