### ISSUE TITLE
Pressing ENTER in the text boxes in the Connection Dialog doesn't trigger default action (e.g. Connect)

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18517] opened 2024-12-17 17:23 UTC
Steps to Reproduce:

1. Open Connection Dialog and fill out parameters in text boxes
2. Press ENTER

Expected: The default Connect action is expected.  The Connect button should be disabled until all required parameters are populated, in which case ENTER would do nothing since the default action was currently disabled.

Actual: No action.

**Comment by Benjin** [comment] 2024-12-18 20:39
Closing as duplicate of https://github.com/microsoft/vscode-mssql/issues/18004

**Closed by Benjin** 2024-12-18 20:39 UTC
Labels: Bug, Area - Connection, Triage: Done
