### ISSUE TITLE
Integrated Support on Linux is not working.

### ISSUE THREAD

**Issue by jonfen** [microsoft/vscode-mssql#1271] opened 2019-08-07 23:22 UTC
- MSSQL Extension Version: 1-37.0-insider
- VSCode Version: 1-37.0-insider
- OS Version: 18.04.3 LTS

Steps to Reproduce:

1.  Follow https://github.com/Microsoft/vscode-mssql/blob/master/KERBEROS_HELP.md#setup-kerberos-on-linux
2.  `root@8a901be64f3e:/app/app-web# kinit jonfen@DOMAIN.LOCAL`
`Password for jonfen@DOMAIN.LOCAL: `
`root@8a901be64f3e:/app/app-web# klist`
`Ticket cache: FILE:/tmp/krb5cc_0`
`Default principal: jonfen@DOMAIN.LOCAL`
`Valid starting       Expires              Service principal`
`08/07/2019 17:09:19  08/08/2019 03:09:19  krbtgt/DOMAIN.LOCAL@DOMAIN.LOCAL`
3. F1--> MS SQL: Connect (fill out defaults)

> mssql: Failed to connect: Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (Server not found in Kerberos database).
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)

**Comment by jonfen** [comment] 2019-12-03 18:06
@abist any ideas?

**Comment by abist** [comment] 2019-12-03 18:51
@jonfen I'm not sure, but looks like this issue is similar to https://github.com/microsoft/azuredatastudio/issues/447 and https://github.com/dotnet/corefx/issues/22184 based on the `kinit` error. I see some resolutions in those threads. Perhaps try the solutions in the thread, and if it still doesn't solve your issue, I'll actively look into this.

**Comment by lgp1985** [comment] 2020-03-03 17:23
Same here. I'm running Ubuntu under WSL.
Followed the steps on the https://github.com/Microsoft/vscode-mssql/blob/master/KERBEROS_HELP.md#setup-kerberos-on-linux
If you check, it should all be fine under klist
```bash
lgpere1@CTC6M5CJZQPQ2:~$ cat /etc/issue
Ubuntu 18.04.4 LTS \n \l

lgpere1@CTC6M5CJZQPQ2:~$ klist
Ticket cache: FILE:/tmp/krb5cc_1000
Default principal: salgpere1@NA.XOM.COM

Valid starting     Expires            Service principal
03/03/20 13:45:04  03/03/20 23:45:04  krbtgt/NA.XOM.COM@NA.XOM.COM
        renew until 03/04/20 13:45:01
03/03/20 13:46:22  03/03/20 23:45:04  krbtgt/XOM.COM@NA.XOM.COM
        renew until 03/04/20 13:45:01
lgpere1@CTC6M5CJZQPQ2:~$ 
```

But while trying to connect with `Server=fqdn-server.mycompany.com;Integrated Security=SSPI;Trusted_Connection=True;`

It'll fail with:

> mssql: Failed to connect: Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication. ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (Decrypt integrity check failed). at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed) at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags) at Microsoft.Data.SqlClient.SNI.SNIProxy.GenSspiClientC...

**Comment by rayrapetyan** [comment] 2022-11-16 20:47
I have the same issue and in my case it's related to GSSAPI, because following works fine:
```
sudo apt install mssql-tools krb5-user
KRB5_TRACE=/dev/stdout kinit -V username@CORP.FOO.COM
(entered password)
/opt/mssql-tools/bin/sqlcmd -S db.corp.foo.com -d Bar
1> SELECT @@VERSION;
2> GO
(outputs server version)
```
But from vscode and AzureDataStudio getting:
>Server not found in Kerberos database

**Comment by cheenamalhotra** [comment] 2022-11-17 03:37
@rayrapetyan Can you confirm you observe the behaviour with latest v1.40 as well?

**Comment by rayrapetyan** [comment] 2022-11-17 04:05
Just checked on v1.40, error looks same:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (Server not found in Kerberos database).
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
   at Microsoft.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[][] serverName)
   at Microsoft.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[][] _sniSpnBuffer)
   at Microsoft.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.SSPIError(String error, String procedure)
   at Microsoft.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at Microsoft.Data.SqlClient.TdsParser.SSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at Microsoft.Data.SqlClient.TdsParser.TdsLogin(SqlLogin rec, FeatureExtension requestedFeatures, SessionData recoverySessionData, FederatedAuthenticationFeatureExtensionData fedAuthFeatureExtensionData, SqlConnectionEncryptOption encrypt)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.Login(ServerInfo server, TimeoutTimer timeout, String newPassword, SecureString newSecurePassword, SqlConnectionEncryptOption encrypt)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass48_0.<CreateReplaceConnectionContinuation>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 312
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 666
ClientConnectionId:42bbd6ab-fda5-456b-bfa2-a027be9de3fd
```

**Comment by cheenamalhotra** [comment] 2022-11-17 04:36
I found a related thread here: https://github.com/dotnet/runtime/issues/75951 
Could you try recommendations to add SPN in the A record? 
If that doesn't help you can also set `dns_canonicalize_hostname` to `false` in `krb5.conf`.

Since ADS uses Microsoft.Data.SqlClient (.NET library), it greatly depends on .NET runtime to be able to resolve hostname.

**Comment by rayrapetyan** [comment] 2022-11-17 05:10
Thanks @cheenamalhotra! I don't have permissions for corp DNS, but `dns_canonicalize_hostname = false` resolved the issue for me in both vscode and azuredatastudio!

**Comment by cheenamalhotra** [comment] 2022-11-17 05:46
I will close this issue since the original issue is 3 yrs old and as confirmed, Kerberos authentication works as expected in Unix platforms.

**Closed by cheenamalhotra** 2022-11-17 05:46 UTC
Labels: Bug, Area - Connection
