### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by samdruster** [microsoft/vscode-mssql#16970] opened 2021-03-20 10:46 UTC
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.10.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cssuh** [comment] 2021-04-19 20:20
Duplicate of https://github.com/microsoft/vscode-mssql/issues/16975

**Closed by cssuh** 2021-04-19 20:20 UTC
