### ISSUE TITLE
[Suggestion] Include an option to set MSSQL to none by default

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [microsoft/vscode-mssql#17298] opened 2022-03-17 03:58 UTC
Currently, there are options to disable error checking and disable intellisense. Is it possible to have an option to set the MSSQL intellisense option located at the status bar to none by default?

**Comment by Benjin** [comment] 2024-11-08 15:53
From #1749, @eksortso said:

> I've discovered a setting that does basically the same thing. It may be overkill, especially if you have some SQL files worth checking and some that are not.
>
>```json
>    "mssql.intelliSense.enableErrorChecking": false
>```

**Comment by Benjin** [comment] 2024-11-08 18:08
Closing as duplicate of #801 since that has the most chatter.  Please continue discussion over there!

**Closed by Benjin** 2024-11-08 18:08 UTC
