### ISSUE TITLE
New connection not stored if failure during connection

### ISSUE THREAD

**Issue by hjrb** [microsoft/vscode-mssql#17728] opened 2023-06-29 09:50 UTC
- MSSQL Extension Version: 1.19.1
- VSCode Version: 1.79.2
- OS Version: Mac OS Ventura 13.4

Steps to Reproduce:

1. Try to create a new connection profile. That is some effort: lookup the server, lookup the DB, logon...
2. The initial connection fails - for whatever reason
3. The profile is not stored at all but completely lost. Instead crate the profile to save the user input and let the user try to fix the connection issue

**Comment by cheenamalhotra** [comment] 2023-07-05 15:45
Hi @hjrb 

The current behavior is by design that only successful connection profiles are saved to settings file, however if you select yes on "Retry Profile creation" notification, you will get prefilled information in the second attempt and can correct connection profile data.

**Comment by cheenamalhotra** [comment] 2023-07-07 18:41
Closing as this is by-design. 
Alternatively, you can manually add profile as needed, and intellisense support is available in settings.json to help with connection properties.

**Closed by cheenamalhotra** 2023-07-07 18:41 UTC
