### ISSUE TITLE
Can´t find table names

### ISSUE THREAD

**Issue by liamdiaze** [microsoft/vscode-mssql#17777] opened 2023-08-14 15:35 UTC
How could I search for a table? It would be good to right click on "Tables", there would be an option to search tables, and only those tables are displayed, as well as disable the find, so that they are all displayed.

**Comment by kburtram** [comment] 2024-08-19 18:27
This looks like a duplicate of https://github.com/microsoft/vscode-mssql/issues/1445.  We're planning to implement an Object Explorer Filtering dialog that will support this scenario.

**Closed by kburtram** 2024-08-19 18:27 UTC
Labels: Enhancement, Area - Object Explorer
