### ISSUE TITLE
command 'mssql.runQuery' not found

### ISSUE THREAD

**Issue by A154858** [microsoft/vscode-mssql#17767] opened 2023-08-03 18:13 UTC
- MSSQL Extension Version: 1.20.0
```
Name: SQL Server (mssql)
Id: ms-mssql.mssql
Description: Develop Microsoft SQL Server, Azure SQL Database and SQL Data Warehouse everywhere
Version: 1.20.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql
```
- VSCode Version: 

```
Version: 1.80.2 (system setup)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:40:28.909Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044 
```
- OS Version: Windows 10

Steps to Reproduce:

1. Update to latest version of VS Code
2. Run any SQL command 

Going back to V1.19.1 solved the issue

**Comment by Charles-Gagnon** [comment] 2023-08-03 18:16
@A154858 Is this the same error you mentioned here? https://github.com/microsoft/vscode-mssql/issues/1087#issuecomment-1664413044

`[ERROR] TypeError: Cannot read properties of undefined (reading 'getProxyAgentOptions')`

You can also use 1.20.0 if you manually download the SQL Tools Service package and unzip it in the extensions directory as mentioned here : https://github.com/microsoft/vscode-mssql/issues/17755#issuecomment-1654764914

**Comment by cheenamalhotra** [comment] 2023-08-07 21:01
I will close this as duplicate of other similar issues we have, as discussed above.

**Closed by cheenamalhotra** 2023-08-07 21:01 UTC
