### ISSUE TITLE
Allow debugging of SQL scripts

### ISSUE THREAD

**Issue by adisoftware** [microsoft/vscode-mssql#1446] opened 2019-10-18 10:12 UTC
Now that the latest SSMS has dropped the ability to debug SQL scripts, it would be great if this VS Code plugin allowed it. Basic features like step through, step into sprocs, etc, with a view of variable values and outputs etc.

**Comment by dr-dba** [comment] 2020-09-03 16:18
+1
I would strongly support that suggestion.
How on the earth any language can programmed without debugger?
How this extension can be useful without debugger?

Please give any response, is it planned? 

I would develop my own t-sql debugger, 
but cant find any debug protocol description for t-sql.
Anybody knows by chance?

**Comment by kburtram** [comment] 2024-08-15 19:07
Closing as a duplicate of https://github.com/microsoft/vscode-mssql/issues/900.

**Closed by kburtram** 2024-08-15 19:07 UTC
Labels: Enhancement, Area - Shell
