### ISSUE TITLE
Add Table Icon In Intellisense

### ISSUE THREAD

**Issue by xsoheilalizadeh** [microsoft/vscode-mssql#895] opened 2017-06-09 06:43 UTC
- MSSQL Extension Version: 1.0.0
- VSCode Version: 1.13.0
- OS Version: Win10 

When I Write SQL do not show Table Icon side Tables Name, please do this.

![2017-06-09_11-11-38](https://user-images.githubusercontent.com/22220356/26963928-87d64c20-4d04-11e7-80ae-cfc119faacf5.gif)

**Comment by kevcunnane** [comment] 2017-06-14 17:30
So the request is not to show icons in the intellisense results?

**Comment by SoheilAlizade** [comment] 2017-06-22 20:02
@kevcunnane yes

**Comment by kburtram** [comment] 2024-08-14 20:08
Thanks for this suggestion.  I'll close this older issue as "By Design" based on lack of upvotes since this functionality has been available.

**Closed by kburtram** 2024-08-14 20:08 UTC
Labels: Enhancement, Area - Language Service
