### ISSUE TITLE
what URL format that mssql accepts to connect a sqlserver? 

### ISSUE THREAD

**Issue by yadongyaly** [microsoft/vscode-mssql#17915] opened 2024-06-27 22:58 UTC
- MSSQL Extension Version: 1.22.1
- VSCode Version:1.90.2
- OS Version: Windows 11 Enterprise

Not a bug, I could not find an answer online so post my question here. 
I am working on TypeScript project, trying to use windows.open(URL, _self) to connect a database with VSC mssql extension, but I cannot find a correct URL format that mssql extension accepts. 

For example, I tried this: 
const URL = `vscode://ms-mssql.mssql//connect?server=${server}&database=${database}&authenticationType=AzureMFA`;
window.open(URL, "_self");

After running, the vscode app pops out a windows saying "do you want to open this URL with mssql extension, and I clicked yes. However, nothing happens after that. 

There is an example of opening Azure Data Studio, it works well, I am looking for something similar with VSC mssql extension. 
const URL = `azuredatastudio://openConnectionDialog?server=${server}&database=${database}&authenticationType=AzureMFA`;

**Comment by Charles-Gagnon** [comment] 2024-06-28 16:25
This extension doesn't currently support that, so unfortunately you won't be able to connect directly with a URI like you can in ADS

**Comment by yadongyaly** [comment] 2024-06-28 17:43
Thanks @Charles-Gagnon for confirming this. I will look around for alternatives then

**Comment by Charles-Gagnon** [comment] 2024-07-08 20:25
@yadongyaly FYI - another tracking issue has been opened for supporting this. You can follow that for updates.

https://github.com/microsoft/vscode-mssql/issues/17920

I'll close this as it's a duplicate of that.

**Closed by Charles-Gagnon** 2024-07-08 20:25 UTC

**Comment by yadongyaly** [comment] 2024-07-08 20:27
[like]  Yadong Lyu reacted to your message:
________________________________
