### ISSUE TITLE
Retry functionality after failed connection opening old Connection experience

### ISSUE THREAD

**Issue by croblesm** [microsoft/vscode-mssql#18148] opened 2024-10-08 01:09 UTC
Whenever I made changes to an existing database instance (like updating the password), to force an update in one of my existing saved connections. 

When I got the error, I see the "**Retry**" option at the bottom of VS Code (***as expected***):

![image](https://github.com/user-attachments/assets/7e843c48-4271-45cc-bcab-c896df18e65d)

However, after selecting the "**Retry**" button. The old connection panel opens up in VS Code command palette:
![image](https://github.com/user-attachments/assets/ed10b3c1-8fbd-407d-b3df-edc233e7e5aa)

I was expecting to see the new Connection Dialog panel.

**Comment by Benjin** [comment] 2024-10-10 21:13
Bug occurs when opening an existing saved connection to a database that isn't accessible.  Not when editing or creating a new connection

**Comment by Benjin** [comment] 2024-11-08 18:52
Duplicate of https://github.com/microsoft/vscode-mssql/issues/18100

**Closed by Benjin** 2024-11-08 18:52 UTC
Labels: Bug, Area - Connection, Triage: Done, Pri: 0
