### ISSUE TITLE
Color Coded Connections

### ISSUE THREAD

**Issue by gavdraper** [microsoft/vscode-mssql#956] opened 2017-07-20 10:48 UTC
I've no idea if this is possible but it would be really handy if you could assign each connection a color and change the background color of the connection name in the bottom right of the window. It would be even better if this could change the tab color but I'm guessing that's not possible.

It's a feature I use all the time in SSMS and is really handy for making sure you're running on the right connection

**Comment by kevcunnane** [comment] 2017-07-20 17:30
As you said we probably can't change the VSCode coloring (unless they've added a nice API for that) but we can see if we can alter some color to indicate this. I'll backlog it for now and see if anyone is interested in investigating.

**Comment by abist** [comment] 2019-12-14 00:56
Closing this issue as a duplicate of https://github.com/microsoft/vscode-mssql/issues/703. Feel free to track that issue instead.

**Closed by abist** 2019-12-14 00:56 UTC
Labels: backlog, enhancement
