### ISSUE TITLE
Open/Peek Definition is picky about source of text

### ISSUE THREAD

**Issue by julielerman** [microsoft/vscode-mssql#936] opened 2017-07-14 19:04 UTC
- MSSQL Extension Version: 1.1.0
- VSCode Version: 1.14.1
- OS Version: Windows 10

Steps to Reproduce:

1. Put mouse over table name in text 'Create Table MySchema.MyTable' and choose peek or open definition
response is MyTable not found
Note that Create Table MySchema.MyTable is the first line of a multi line statement
2. Put mouse over table name in text 'Select * from MySchema.MyTable', and choose peek or open definition
Definition is displayed

ALso not seeing pop up info when hovering over MyTable in Create Table but I do in Select statement. I'm guessing that mssql has to process the statement for discovery and it just can't do that with the create table statement? It seems natural to want to do that right after creating a table to verify the schema rather than having to type some random sql in order to do so.

**Comment by kburtram** [comment] 2024-08-14 20:18
Closing this older issue as "By Design/Won't Fix".  It is a limitation that Go to Definition doesn't work on CREATE TABLE statements.  The full schema from the server can be scripting using the Script as CREATE option in the Object Explorer content menu as a possible workaround.

**Closed by kburtram** 2024-08-14 20:18 UTC
Labels: Bug, Area - Query Editor
