### ISSUE TITLE
Exception executing query with new result grid

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18212] opened 2024-10-15 20:12 UTC
Steps to Reproduce:

1. Run a couple queries and interact with messages pane and switch around in the UI, like hiding the panel/showing it again.  I'll try to narrow down the steps exactly
3. Run another query

Expected: All the queries work

Actual: I hit the below error.

```
[ExtensionListenerError] Extension 'ms-mssql.mssql' FAILED to handle event: TypeError: Cannot read properties of undefined (reading 'webview'): Error: [ExtensionListenerError] Extension 'ms-mssql.mssql' FAILED to handle event: TypeError: Cannot read properties of undefined (reading 'webview')
    at gh.value (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:35184)
    at T.B (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
    at T.C (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:802)
    at T.fire (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:1019)
    at gh.value (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:155:61240)
    at T.B (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
    at T.fire (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:950)
    at nw.acceptDocumentsAndEditorsDelta (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:121:11570)
    at nw.$acceptDocumentsAndEditorsDelta (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:121:10040)
    at Zb.S (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113896)
    at Zb.Q (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113676)
    at Zb.M (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112765)
    at Zb.L (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111870)
    at gh.value (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110667)
    at T.B (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
    at T.fire (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:950)
    at no.fire (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9399)
    at gh.value (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13273)
    at T.B (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
    at T.fire (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:950)
    at no.fire (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9399)
    at MessagePortMain.<anonymous> (file:///c:/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11562)
    at MessagePortMain.emit (node:events:519:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619)
```

This displayed in UI, as

![Image](https://github.com/user-attachments/assets/294d9537-4942-4c1b-8fd7-d60f54b2352b)

and then the editor windows is stuck in broken state.

![Image](https://github.com/user-attachments/assets/2c8aaba9-1f77-4a0d-87ed-fd6e3c24a4b7)

**Comment by kburtram** [comment] 2024-10-15 20:15
Ahh, it looks like the problem is when the query doesn't generate a result set, but only messages, e.g., `PRINT 'I swear the coffee machine is sentient'`.

**Comment by caohai** [comment] 2024-10-15 20:19
This seems to be a regression, queries without a result set used to work fine, I'm taking a look

**Comment by caohai** [comment] 2024-10-15 20:50
@kburtram This regression appears to be introduced by the STS vbump in https://github.com/microsoft/vscode-mssql/pull/18177, I was able to get `PRINT` running if I downgrade STS to `5.0.20240918.1` in main, taking a closer look at STS side changes right now.

**Comment by caohai** [comment] 2024-10-15 21:58
Root cause:
STS PR https://github.com/microsoft/sqltoolsservice/pull/2400 brought in MDS `5.2.0` which contains a regression https://github.com/dotnet/SqlClient/issues/2388. The issue was later fixed in a hot release.
I'll send out a PR to bump MDS to `5.2.2` in STS.
cc @kburtram @aasimkhan30  @Bhavikshah123

**Comment by caohai** [comment] 2024-10-15 22:06
Seeing same error with old query result implementation
![Image](https://github.com/user-attachments/assets/4a51821b-c9da-4ee0-946d-bbc543c9d27c)

**Closed** 2024-10-16 06:07 UTC
Labels: Bug, Triage: Done, Pri: 0, Area - Query Result
