### ISSUE TITLE
SQL Tools Service component could not start.

### ISSUE THREAD

**Issue by panyang1217** [microsoft/vscode-mssql#1071] opened 2018-03-16 01:55 UTC
- MSSQL Extension Version: 1.3.0
- VSCode Version: 1.21.0
- OS Version:  Microsoft Windows Server 2016 Datacenter | 10.0.14393 N/A Build 14393

Steps to Reproduce:

1. Start VSCode and open any .sql file, i got an error about "mssql: SQL Tools Service component could not start."
2. The SqlToolsService output i find the following exception info.

> Unhandled Exception: Microsoft.SqlServer.Management.SqlParser.SqlParserInternalParserError: Internal Parser Error ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.SqlServer.Management.SqlParser.SqlCodeDom.SqlCodeObject.SetParentPointers()
   at Microsoft.SqlServer.Management.SqlParser.SqlCodeDom.SqlCodeObject.SetParentPointers()
   at Microsoft.SqlServer.Management.SqlParser.SqlCodeDom.SqlCodeObject.SetParentPointers()
   at Microsoft.SqlServer.Management.SqlParser.SqlCodeDom.SqlCodeObject.SetParentPointers()
   at Microsoft.SqlServer.Management.SqlParser.SqlCodeDom.SqlCodeObject.SetParentPointers()
   at Microsoft.SqlServer.Management.SqlParser.SqlCodeDom.SqlCodeObject.SetParentPointers()
   at Microsoft.SqlServer.Management.SqlParser.SqlCodeDom.SqlStatement.SetParentPointers()
   at Microsoft.SqlServer.Management.SqlParser.SqlCodeDom.SqlCodeObject.SetParentPointers()
   at Microsoft.SqlServer.Management.SqlParser.SqlCodeDom.SqlCodeObject.SetParentPointers()
   at Microsoft.SqlServer.Management.SqlParser.Parser.Internals.VersionedParserBase.Parse(Boolean isIncremental, String sql, SqlScript prevScript, ParseOptions options, ParseOptions& resultOptions)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.SqlParser.Parser.Internals.VersionedParserBase.Parse(Boolean isIncremental, String sql, SqlScript prevScript, ParseOptions options, ParseOptions& resultOptions)
   at Microsoft.SqlServer.Management.SqlParser.Parser.Parser.Parse(Boolean isIncremental, String sql, ParseResult prevResult, ParseOptions options, ParseOptions& resultOptions)
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.LanguageService.<>c__DisplayClass60_0.<ParseAndBind>b__0() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\LanguageService.cs:line 769
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[Error - 1:44:29 AM] Connection to server got closed. Server will not be restarted.

**Comment by MattIrv** [comment] 2018-03-16 18:23
Thanks for reporting this. Do you know what version of SQL Server you're connecting to when this happens and whether it happens for all connections or just for a specific server?

**Comment by panyang1217** [comment] 2018-03-23 10:03
I get this error when I connected to AzureSql. And I found that set "mssql.intelliSense.enableIntelliSense" to false this error gone.

**Comment by AbdulSami0098** [comment] 2019-05-01 17:03
I am facing the same issue. What should i do?

**Comment by kburtram** [comment] 2019-05-01 17:06
@AbdulSami0098 are you seeing the same SqlParser exception in the original issue post?  @shueybubbles do you have any context on that particular exception?

**Comment by AbdulSami0098** [comment] 2019-05-01 17:08
mssql extension version is 1.6.0

**Comment by AbdulSami0098** [comment] 2019-05-01 17:10
@kburtram yes same.

**Comment by shueybubbles** [comment] 2019-05-01 17:26
Do you happen to have any access to the master database on that Azure Sql logical server?

**Comment by AbdulSami0098** [comment] 2019-05-01 18:06
Let me explain. It was working perfectly everything was fine and my system crashed and restarted. After that i am facing this issue. I have tried uninstalling and reinstalling the mssql extension but i am still facing the same issue.

**Comment by shueybubbles** [comment] 2019-05-01 18:10
oh there may be some corrupted settings data in your user profile, then. I think the settings are put in %userprofile%\AppData\Roaming\Code , maybe rename that folder and see if code and the extension start up ok

**Comment by AbdulSami0098** [comment] 2019-05-01 18:40
Please specify which folder should i rename?

**Comment by shueybubbles** [comment] 2019-05-01 18:42
The Code folder. Code will recreate one when it starts. you can then copy individual files back over from the old one if there are particular settings you want to recover.

**Comment by AbdulSami0098** [comment] 2019-05-01 18:48
Still i am having same issue

**Comment by shueybubbles** [comment] 2019-05-01 19:16
the only thing I could think of is to open a blank sql file and connect, then use a debugger that saves a DMP file (like visual studio) to attach to the microsoftsqltoolsservicelayer process. Then reproduce the problem and let the debugger break on the exception.  Then save a full memory dump  to take a look at it. We could share the debugging session over visual studio live share to avoid the need for you to share the dmp with us directly, as the dmp may have passwords in memory etc. I can provide PDB files for the relevant DLLs as needed.

**Comment by kburtram** [comment] 2019-06-05 23:21
I'm going to close this bug since we don't have a repo.  Please try again with the latest build since it has several updates to the components listed in the original callstack.

**Closed by kburtram** 2019-06-05 23:21 UTC
Labels: bug
