### ISSUE TITLE
Connection profile not showing newly added connections

### ISSUE THREAD

**Issue by tadcrazio** [Microsoft/vscode-mssql#953] opened 2017-07-18 17:27 UTC
- MSSQL Extension Version: 1.0.0
- VSCode Version: 1.15.0-Insider
- OS Version: Windows 8.1

Steps to Reproduce:

1. Got o File>preferences>Settings under user settings add connection profiles. 
2.Press cntrl + shift + C newly added connections are not appearing. 
3.) refreshing window, restarting computer. Connections still do not show.

**Comment by kevcunnane** [comment] 2017-07-18 19:09
@tadcrazio we've just updated to a new version that has a fix related to this. Previously if errors such as extra `,` in the settings.json occurred, we would fail to read the connections. Now we should be tolerant to this. Could you please try the following:
- Update the `mssql` extension to v1.1 from the Extensions viewlet in VSCOde
- Ensure your settings file is saved after adding new connections
- Try again to list the new connections.

**Comment by tadcrazio** [comment] 2017-07-18 20:20
Thanks @kevcunnane  when was the update pushed out? I don't see any updates available in vscode.

**Comment by tadcrazio** [comment] 2017-07-18 20:24
New Version installed. I still do not see my newly created connections. Anything else I can try?

**Comment by kevcunnane** [comment] 2017-07-18 20:27
Can you send a sample of your settings file? PLease remove any sensitive information (e.g. change server names, db names, ensure no password is listed). Also is it in your User Settings?

**Comment by tadcrazio** [comment] 2017-07-18 20:34
It is in my User Settings.

`"mssql.connections": [
    {
        "server": "SQL-ENV-L-SERV01.Contoso.host",
        "database": "Account",
        "authenticationType": "SqlLogin",
        "user": "sq_username",
        "password": "",
        "savePassword": true
    },
    {
        "server": "SQL-ENV-L-SERV02.Contoso.host",
        "database": "",
        "authenticationType": "SqlLogin",
        "user": "sq_userName",
        "password": "",
        "savePassword": true
    },
    {
        "server": "SQL-ENV-L-SERV03.Contoso.HOST,1433",
        "database": "",
        "authenticationType": "Integrated",
        "password": ""
    },
    {
        "server": "SQL-ENV-L-SERV04.Contoso.HOST,1433",
        "database": "",
        "authenticationType": "Integrated",
        "password": ""
    },
    {
        "server": "SQL-ENV-L-SERV05.development.Contoso.com,1433",
        "database": "",
        "authenticationType": "Integrated",
        "password": ""
    },
    {
        "server": "SQL-ENV-L-SERV06.development.Contoso.com,1433",
        "database": "",
        "authenticationType": "Integrated",
        "password": ""
    }
]`

**Comment by kevcunnane** [comment] 2017-07-18 20:49
Ah - I'm so sorry I missed this, but I now know what the issue is. We have a known issue where we always read from the VSCode settings rather than detecting if we're in Insiders build and using that instead. The basic thing is we have an array and want to merge workspace and user connections, so don't have a great way to do that while using the built-in settings service.

So to work around, please copy the connections array into the VSCode settings file instead of the Insiders file. This is `%APPDATA%\Code\User\settings.json` on Windows.

**Comment by kevcunnane** [comment] 2017-07-18 20:50
Adding this to our 1.2 milestone. We need a better solution so Insiders users don't have to put connections in the VSCode settings file. We should respect the fact that Insiders build has its own settings.

**Comment by tadcrazio** [comment] 2017-07-19 11:51
Ah thank you.

**Comment by kevcunnane** [comment] 2017-07-19 16:20
@tadcrazio I was doing some further digging into this. Good news - looks like they've added the exact API we need to resolve this. So we can definitely get this done for our next release, it's a long-standing ask.

Speaking of - we are tracking this already in #242 and indeed have this as a known issue in our wiki. Since that's the original tracker I'm going to close this our and use that as the tracker. I've made sure it's marked on our 1.2 release milestone so when we start working on that we'll try to get this done.

**Closed by kevcunnane** 2017-07-19 16:20 UTC
Labels: bug, customer issue

**Comment by tadcrazio** [comment] 2017-07-20 12:28
That's good news, thanks again !
