### ISSUE TITLE
Result windows disappear

### ISSUE THREAD

**Issue by cantruchd** [microsoft/vscode-mssql#17130] opened 2021-11-23 23:42 UTC
- MSSQL Extension Version: v1.11.1
- VSCode Version: 1.62.3(System Set up)
- OS Version: Windows 10 Pro 21H1

Steps to Reproduce:

1. After running SQL Script the result windows does not appear
![ảnh](https://user-images.githubusercontent.com/2477766/143146079-8b824506-d9ef-4d66-91cd-7c35e618a7d6.png)

**Comment by abist** [comment] 2021-11-29 20:20
@cantruchd As you can see, there seems to be an error in your query here and hence it has no results. The error is shown in the `Messages` area.

**Comment by kburtram** [comment] 2021-12-01 18:06
@cantruchd I'll close this as "by design".  The intended design is that if the query only returns an error and no results then the results grid is not displayed.  If the query had multiple batches and only some batches had errors and others returned results you should see both the error messages and results.  Please let us know if this isn't that you're seeing.  Thanks!

**Closed by kburtram** 2021-12-01 18:06 UTC
