### ISSUE TITLE
New Feature: When Using Integrated Allow To Enter Credentials

### ISSUE THREAD

**Issue by ssmehaffie** [microsoft/vscode-mssql#826] opened 2017-04-20 19:14 UTC
- MSSQL Extension Version: 3.0.0
- VSCode Version: 1.11.2
- OS Version: Windows 7

I would like to be able to enter windows credentials when using integrated security.  That way I can access database in a differene domain other than the one I am logged into (examples: test\username, qa/username).  This would overcome a limitation of SSMS where you have to do a RunAs command to access database in different domains (otherwise you get error about untrusted domain).

Steps to Reproduce:

1. When you choose integrated you can only access databases in the domain you are in,
2. If you try to access a database in a different domain you get an "untrusted domain" error becuase it uses the user you are logged in as and not the user you are for the domain the database is in.

**Comment by kevcunnane** [comment] 2017-04-21 17:07
@smehaffie thanks for this suggestion. At this point, we are limited in the same way SSMS is regarding this - we use the ADO.Net APIs in .Net Core for connection which do not, to my knowledge, support this. However we've heard about this twice so should keep it on our backlog and see if we can engage with the connectivity folks to understand if this is a feasible request.

**Comment by ChadWLiu** [comment] 2017-12-07 05:09
I'm in the similar situation.

OS: Ubuntu 16.04.2 LTS
VSCode: 1.18.1
MSSQL Extension: 1.2.1

The workstation is not joined into domain.

I'm trying to follow the guide [here](https://github.com/Microsoft/vscode-mssql/blob/master/KERBEROS_HELP.md)

SPN at SQL side is correctly setup and can be confirmed Kerberos connection is successfully established.

Step 0 to Step 3 are completed without issue. `klist` shows up the correct ticket generated. However, the connection to SQL instance throws the following error.

```
mssql: Error 18452: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication 
```

**Comment by deweter** [comment] 2017-12-27 14:36
VSCode-mssql is using  .Net Core 2.0 now. Is it already possible to implement dialog for alternate windows credentials when connection from Windows?

**Comment by ssmehaffie** [comment] 2018-08-13 05:54
Any update on this?  This feature really is needed for enterprise users of VS code.

**Comment by JordanTheITGuy** [comment] 2019-07-31 17:12
This would also be nice for users that don't want to run VSCode with their elevated token all the time. Example my normal user account doesn't have rights, in general a "run as" account for the connection would be really nice. (Nice for PowerShell too)

**Comment by kburtram** [comment] 2024-08-14 19:26
Unfortunately, this is still not supported in the SQL Client driver and there are no plans to support this in that upstream dependency.  Due to this I'll close as "Won't Fix/By Design".

**Closed by kburtram** 2024-08-14 19:26 UTC
Labels: Enhancement, Area - Connection, Triage: Done
