### ISSUE TITLE
Ambiguous column error shown when selecting a field and "*"

### ISSUE THREAD

**Issue by bergamin** [Microsoft/vscode-mssql#773] opened 2017-03-10 13:01 UTC
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.10.2
- OS Version: Windows 7

Steps to Reproduce:

1. Select a field and * from one table and order by the field you specified
2. It will consider the second appearance of the field in the "*" as if it was ambiguous, even though the query runs normally as you would expect.

![pngtemp](https://cloud.githubusercontent.com/assets/14339291/23796133/1dc843fc-0578-11e7-9726-ce6900b28e5e.png)

**Comment by abist** [comment] 2017-03-16 00:02
Thank you for raising this issue @bergamin. This is a legitimate problem and we'll be looking into fixes for this issue :)

**Comment by kburtram** [comment] 2017-03-24 17:54
@abist SMO has been updated to RC3.  Please recheck the scenario.

**Comment by abist** [comment] 2017-04-11 18:56
@kburtram reproducible in RC3

**Comment by kburtram** [comment] 2017-04-11 19:04
@abist did you determine if this is an issue in SQL parser or in the .Net Core port of SQL parser?

**Comment by abist** [comment] 2017-04-11 20:07
@kburtram I'm not sure where the issue is, but I can reproduce it in the latest SSMS as well.

**Comment by kevcunnane** [comment] 2017-04-21 19:30
@abist - this is a regression in SMO if it also occurs in SSMS. We should raise this with the core team and get them to investigate.

**Comment by abist** [comment] 2017-07-12 19:07
@bergamin Hey, the reason we get that error is because it's invalid T-SQL. The column `Descricao_Longa` in your case is indeed an ambiguous column. This is because when we order by this column, this column is present in both `*` and `Descricao_Longa` itself. To achieve what you're trying to do here, you can have a table alias something like this - 

```
select Codigo
         ,Descricao_Longa
        ,*
from produtos i
order by i.Descricao_Longa
```
We gave the table an alias `i`, and so it's not ambiguous any more. 
I'll go ahead and close this issue, feel free to open if you have more problems.

**Closed by abist** 2017-07-12 19:07 UTC
Labels: bug, customer issue

**Comment by bergamin** [comment] 2017-07-13 19:36
Fair enough...

Anyway, the interesting part of it is that it is not considered invalid SQL when run, and Microsoft SQL Server Management Studio doesn't show this as invalid either (I might be running an old one, though. Both Management Studio and SQL Server database because of client specifications that are quite complicated to explain hehehe)

I'm just glad that this extension won't block the execution because of this.

Thank you!
