### ISSUE TITLE
Dates should be ISO formatted

### ISSUE THREAD

**Issue by kristofferostlund** [Microsoft/vscode-mssql#570] opened 2016-12-29 09:12 UTC
It would be great if the date formatting would follow an ISO standard (namely ISO 8601) instead of the US style way of writing dates (`2016-12-29T08:58:36.226Z` over `12/29/2016 08:58:36`) as this would reduce possible confusion with dates such as `01/05/2016` which at a glance may look like May 1, 2016 instead of 5 January, 2016 ([See here](http://www.iso.org/iso/home/standards/iso8601.htm)).

Another solution would be to make this configurable in the config file.

---

- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8.1
- OS Version: OS X El Capitan (10.11.6)

Steps to Reproduce:

1. Select a field with a type of date `SELECT GETUTCDATE() AS [now]`

![screen shot 2016-12-29 at 09 55 37](https://cloud.githubusercontent.com/assets/9280031/21540081/029d82b6-cdad-11e6-992e-6a602ea14818.png)

**Comment by kristofferostlund** [comment] 2016-12-29 09:18
It seems this is because dates are formatted by `.toLocaleString()` instead of `.toISOString()`.

**Comment by benrr101** [comment] 2016-12-29 23:29
Thanks for reporting this bit of feedback! A couple weeks back, I made a change to support displaying milliseconds in DATETIME2 fields. The additional goal of this was to make sure that any DATE, DATETIME, or DATETIME2 fields appeared the same way that they did in SSMS. Those changes were made but needed to be backed out due to a regression in displaying DATE fields. The more robust changes have been made and checked in (https://github.com/Microsoft/sqltoolsservice/pull/196) but just missed the cut for the latest release. 

This change should also address your request. SSMS formats date columns as *almost* the ISO format you listed. It uses `2016-12-29 08:58:36.226`. I confirmed that this is the format that SSMS uses even in locales that use `,` instead of `.` for decimals. Can you confirm that this is a satisfactory solution?

**Comment by kristofferostlund** [comment] 2016-12-30 13:56
That absolutely sounds like a good enough solution, thank you! Is there a time frame for when this will be merged and released?

**Comment by kevcunnane** [comment] 2017-01-03 17:54
@kristofferostlund we will have it available in a nightly build this week which would let you test. We haven't locked down an exact timeframe for our next marketplace update, but will be adding the timelines to the [Projects](https://github.com/Microsoft/vscode-mssql/projects) page as we get this planned out.

**Comment by benrr101** [comment] 2017-01-04 18:59
Since this fix is checked into our dev build, has been released in our latest few nightly builds, and is in the pipeline for next release, I'll close this issue up.

**Closed by benrr101** 2017-01-04 18:59 UTC
Labels: customer issue
