### ISSUE TITLE
Query Results Only Appear on Second Execute After Cancelling Out of Connection Profile Picker 

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/vscode-mssql#1315] opened 2019-09-24 21:08 UTC
Steps to Reproduce:

1. From Command Palette, choose "MS SQL: New Query"
2. Press escape to get rid of quick pick menu when asked for a connection profile
3. Write query
4. Use keyboard shortcut/right click to execute the query
<No results shown, nothing appears to happen>
5. Execute query a second time
<Now results are shown>

**Comment by abist** [comment] 2019-09-25 17:51
Closing this as duplicate of https://github.com/microsoft/vscode-mssql/issues/1327

**Closed by abist** 2019-09-25 17:51 UTC
Labels: bug
