### ISSUE TITLE
CASE Statement - Inconsistent Formatting

### ISSUE THREAD

**Issue by Emeka-MSFT** [microsoft/vscode-mssql#17222] opened 2022-01-25 17:54 UTC
# CASE Statement - Inconsistent Formatting

## Repro
Launch VSCODE, and ensure MSSQL extension is installed and enabled.
Save the following (unformatted) to a .SQL file, and format it (e.g. using `SHIFT+ALT+F`

## Original (un-formatted)
```sql
SELECT SYSUTCDATETIME() AS "time",
       @@SERVERNAME AS "server",
       CASE       WHEN rg.replica_type = 0 THEN 'Primary'
         WHEN rg.replica_type = 1 THEN 'Secondary'
  ELSE NULL
      END
       AS "replica"
FROM sys.dm_user_db_resource_governance AS rg
WHERE rg.database_id = DB_ID();
```

## Formatted By MSSQL
```sql
SELECT SYSUTCDATETIME() AS "time",
    @@SERVERNAME AS "server",
    CASE       WHEN rg.replica_type = 0 THEN 'Primary'
         WHEN rg.replica_type = 1 THEN 'Secondary'
  ELSE NULL
      END
       AS "replica"
FROM sys.dm_user_db_resource_governance AS rg
WHERE rg.database_id = DB_ID();
```

## Expected (option1)
```sql
SELECT SYSUTCDATETIME() AS "time",
    @@SERVERNAME AS "server",
    CASE
        WHEN rg.replica_type = 0 THEN 'Primary'
        WHEN rg.replica_type = 1 THEN 'Secondary'
        ELSE NULL
    END
    AS "replica"
FROM sys.dm_user_db_resource_governance AS rg
WHERE rg.database_id = DB_ID();
```

## Expected (option2)
```sql
SELECT SYSUTCDATETIME() AS "time",
    @@SERVERNAME AS "server",
    CASE WHEN rg.replica_type = 0 THEN 'Primary'
        WHEN rg.replica_type = 1 THEN 'Secondary'
        ELSE NULL
    END
    AS "replica"
FROM sys.dm_user_db_resource_governance AS rg
WHERE rg.database_id = DB_ID();

```

**Comment by kburtram** [comment] 2024-08-16 17:31
Closing as duplicate of https://github.com/microsoft/vscode-mssql/issues/733

**Closed by kburtram** 2024-08-16 17:31 UTC
Labels: Area - Formatter
