### ISSUE TITLE
command 'extension.connect' not found

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode-mssql#448] opened 2016-12-02 22:18 UTC
_From @arvindravish on December 1, 2016 20:39_

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|vscode-color|anseki|0.2.2|
|theme-onedark|azemoh|0.4.0|
|plsql|casian|0.0.2|
|python|donjayamanne|0.5.5|
|xml|DotJoshJohnson|1.6.0|
|terminal|formulahendry|0.0.5|
|Theme-azure|gerane|0.0.2|
|Theme-FlatlandMonokai|gerane|0.0.4|
|Theme-monokai-best|gerane|0.0.2|
|prettify-json|mohsen1|0.0.3|
|mssql|ms-mssql|0.1.5|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|team|ms-vsts|1.108.0|
|startanyshell|remcoros|0.3.1|
|theme-obsidian|rprouse|0.2.0|
|usql-vscode-ext|usqlextpublisher|0.1.9|
|vim|vscodevim|0.4.4|
|Material-theme|zhuangtongfa|1.0.3|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1. CTRL + SHIFT + P
2. MSSQL:CONNECT

_Copied from original issue: Microsoft/vscode#16342_

**Comment by kburtram** [comment] 2016-12-03 03:23
@arvindravish sometimes we see this message for a short period of time while the extension is being loaded (for example, within a could seconds of loading a SQL file).  Waiting a few seconds for the extension to load such resolve that issue.

If the issue is persistent this would indicate the extension is failing to load.  Are there any error messages shown in the output window?  You could also try uninstalling then reinstalling the mssql extension.

**Comment by johnfredrik** [comment] 2016-12-15 14:31
I had the same problem. To slove the problem for I had to uninstall an extentiong called HTML CSS Class Completion. After doing that it worked. Hope that helps.

**Comment by hmendozap** [comment] 2017-01-03 16:35
I faced with the same problem, reinstalling did solve the issue, but I had no idea about the underlying cause, as my extensions are: c#, latex language support, Material Icon Them, Powershell, Python, gruvbox and vim.

**Comment by kburtram** [comment] 2017-04-24 20:28
I'm going to close this issue since we haven't seen any recent reports on this issue and have done a couple release since the last comment.  Please reactivate if this is still an issue on the current release.

**Closed by kburtram** 2017-04-24 20:28 UTC
Labels: bug, customer issue, needs more info

**Comment by joffies** [comment] 2018-02-20 07:48
Same issue for me...going to attempt a reinstall of the module 
![image](https://user-images.githubusercontent.com/13243938/36412491-6ba0be96-1612-11e8-9a0f-d35e0ae4b24d.png)

**Comment by jet-ham** [comment] 2021-06-01 16:49
i have MacBook m1 and the same problem on Visual Studio Code. 
Visual Studio Code:  Version: 1.55.2, 
SQL Server (mssql): Version: 1.10.1
C#: Version 1.23.12

Command 'MS SQL: Connect' resulted in an error (command 'mssql.connect' not found)
mssql: The platform is not supported
Need help

**Comment by kburtram** [comment] 2021-06-01 18:40
@jet-ham the current extension build doesn't support non-Intel Apple chipsets yet.  We recently took this PR which enables this support with Rosetta enabled, but haven't published a release with this change yet https://github.com/microsoft/vscode-mssql/pull/16969.  If you have a node.js build env it's pretty easy to compile from source to get the fix more quickly but I understand if that is too much effort in the meantime.

**Comment by jet-ham** [comment] 2021-06-02 08:06
thank you for your answer! 
I tried this: https://blog.logrocket.com/docker-sql-server/
But after I enter 'docker-compose logs sql-server-db' in Terminal then I get:
sql-server-db    | SQL Server 2019 will run as non-root by default.
sql-server-db    | This container is running as user mssql.
sql-server-db    | To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
sql-server-db    | /opt/mssql/bin/sqlservr: Invalid mapping of address 0x40037d0000 in reserved address space below 0x400000000000. Possible causes:
sql-server-db    | 1) the process (itself, or via a wrapper) starts-up its own running environment sets the stack size limit to unlimited via syscall setrlimit(2);
sql-server-db    | 2) the process (itself, or via a wrapper) adjusts its own execution domain and flag the system its legacy personality via syscall personality(2);
sql-server-db    | 3) sysadmin deliberately sets the system to run on legacy VA layout mode by adjusting a sysctl knob vm.legacy_va_layout.
sql-server-db    | 


I don't know what to do.

**Comment by jet-ham** [comment] 2021-06-02 12:58
@kburtram how can I do this: "If you have a node.js build env it's pretty easy to compile from source to get the fix more quickly"

i am beginner*

**Comment by ravi-achar** [comment] 2023-04-11 21:02
I am having this problem now. I have tried removing the extension and doing a fresh install. No change in behavior. This was working perfectly file till about 3 weeks ago. 
VS code version details
--------------------------
Version: 1.66.2 (system setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

Exception details
Command 'MS SQL:Connect' resulted in an error (command 'mssql.connect' not found). 

I use VS code on a VM at work due to the small memory footprint. I am almost about to get rid of this extension.
Appreciate any help.

**Comment by ravi-achar** [comment] 2023-04-11 21:23
Nevermind, I uninstalled and updated to version 1.77.1 available in the software center. It did a re-install of all the extensions and the issue is resolved.
