### ISSUE TITLE
Ubuntu 16.04 mssql: SQL Tools Service component could not start.

### ISSUE THREAD

**Issue by henksandoval** [Microsoft/vscode-mssql#901] opened 2017-06-17 22:16 UTC
- MSSQL Extension Version: 1.0.0
- VSCode Version: 1.13.1
- OS Version: Ubuntu 16.04

Good afternoon. I'm trying to use this tool because I really like to install it on my development environment on windows. But me is giving many problems to install it on Ubuntu

Steps to Reproduce:

1. Install extension
2. Type mssql and select vscode-mssql in the list of extensions
3. Visual Studio Code will show you a message confirming successful installation
4. Restart Visual Studio Code when prompted

Error: mssql: SQL Tools Service component could not start.

SqlToolsService Initialization it does not finish

look for the file libunwind in my extension directory, but not this. As I have installed and uninstalled several times the extension

The Command promt output

SQLToolsService

[Error - 18:09:34] Connection to server is erroring. Shutting down server.
[Error - 18:09:34] Connection to server is erroring. Shutting down server.
[Error - 18:09:34] Connection to server is erroring. Shutting down server.
Failed to load /home/has/.vscode/extensions/ms-mssql.mssql-1.0.0/sqltoolsservice/1.0.0/Ubuntu16/libcoreclr.so, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/has/.vscode/extensions/ms-mssql.mssql-1.0.0/sqltoolsservice/1.0.0/Ubuntu16/libcoreclr.so'

**Comment by kevcunnane** [comment] 2017-06-19 16:45
@henksandoval, sorry to hear you are running into this issue. We had reports of this a while back, and it seems the solution was to `apt-get install libunwind8`. This is a dependency for .Net Core and it appears that on some systems it is not there or causes problms

The thread is at https://github.com/Microsoft/vscode-mssql/issues/718. We are actively working on upgrading the tool to .Net Core 2.0 which we believe will resolve this long term. Please let us know if this workaround solves the issue for you.

**Comment by guss77** [comment] 2017-06-20 07:24
Installing `libunwind8` doesn't solve the problem. I had to also install `liblldb-3.6` and manually install `libicu52` from https://packages.ubuntu.com/trusty-updates/libicu52 . After which the mssql extension loaded properly.

**Comment by henksandoval** [comment] 2017-06-20 13:06
Thank you very much for the information, today apply measures and inform you the result

**Comment by kburtram** [comment] 2017-07-17 17:22
The upcoming release will use .net core 2 which will change the per-distro dependencies and support matrix.  I'll close this issue now.  Please reactivate if there are any continued installation issues with the 1.1 release that will be out later this week.  Thanks!

**Closed by kburtram** 2017-07-17 17:22 UTC
Labels: bug, customer issue

**Comment by lootsy** [comment] 2017-09-17 19:44
I'm running into the same issue with error message
**"mssql: SQL Tools Service component could not start."**

* MSSQL Extension Version: 1.1 (up to date)
* VSCode Version: 1.16.1 (up to date)
* OS Version: Ubuntu 16.04 (up to date)

After installing package "libunwind8" by "apt-get install libunwind8" the extension loaded properly.
Please _note_ it in "_known issues_" and try to resolve this dependency. Thanks!

**Comment by burm87** [comment] 2017-10-26 09:42
The issue is still present with these versions:
- MMSQL Extension Version: 1.2 (up to date)
- VSCode Version: 1.17.2 (up to date)
- OS Version: Ubuntu 16.04 (up to date)

Running `sudo apt-get install libunwind8` solved the problem.
