### ISSUE TITLE
Filtering No Longer available

### ISSUE THREAD

**Issue by Data-mite** [microsoft/vscode-mssql#17899] opened 2024-05-08 15:48 UTC
MSSQL Extension Version: 1.22.1
Version: 1.89.0 (user setup)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19044

Upon updating VSCode to 1.89.0, Ctrl-F no longer invokes Filter functionality in the SQL Server Connections window. Previously only partially functional, now completely dead.

Steps to Reproduce:

1. Connect to a server in Connections. 
2. Expand Programmability (Or Tables, Views, Etc.)
3. Press Ctrl-F

If there is an open editor window, the Find applet opens in it. If there is no open explorer window, nothing happens at all. 

The expected response is for a finder applet to open in the connections panel with limited functionality as outlined in #17783

**Comment by kburtram** [comment] 2024-08-20 22:36
Closing as duplicate of https://github.com/microsoft/vscode-mssql/issues/17783.  Thanks for reporting.

**Closed by kburtram** 2024-08-20 22:36 UTC
