### ISSUE TITLE
Result grid doesn't always refresh

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18294] opened 2024-10-22 06:01 UTC
- OS Version: macos

Steps to Reproduce:

1. Run a query
2. Close result grid pane
3. Switch around a few other documents, and the come back to query
4. Open result pane

Expected: Results grid resizes to fill available space.

Actual: Result grid doesn't refresh, but if the panel is resized then that triggers a refresh.

![Image](https://github.com/user-attachments/assets/f3adcbe6-6af2-4bc9-af45-7eb94d33c398)

**Comment by cssuh** [comment] 2024-10-22 17:44
Closing as duplicate of #18276

**Closed by cssuh** 2024-10-22 17:44 UTC
Labels: Bug, Area - Query Result
