### ISSUE TITLE
Keyboard shortcut (CMD+C) doesn't copy in results pane

### ISSUE THREAD

**Issue by robertmiles3** [microsoft/vscode-mssql#18358] opened 2024-11-06 16:34 UTC
I recently updated to the new experience with the extension 1.25.0 which shows the results pane in the same tab (versus the old style of a separate tab). However, when I attempt to copy a cell from the results pane via the keyboard, it will not copy. Copying the cell via context menu (right-click, select "Copy") works fine, but the keyboard shortcut does not.

- MSSQL Extension Version: 1.25.0
- VSCode Version: 1.95.1
- OS Version: macOS Sequoia 15.1

Steps to Reproduce:

1. Run a `SELECT` statement.
2. Select a cell in the results pane.
3. Copy via keyboard (CMD+C for macOS)
4. Attempt to paste anywhere...doesn't work.

**Comment by cssuh** [comment] 2024-11-06 20:02
closing this since it is a duplicate of https://github.com/microsoft/vscode-mssql/issues/18315, please add any comments there!

**Closed by cssuh** 2024-11-06 20:02 UTC

**Comment by robertmiles3** [comment] 2024-11-06 20:04
Great thanks. I searched for "copy" but didn't find it. Thanks!
