### ISSUE TITLE
[Rich Experiences] Result set support in new query results pane

### ISSUE THREAD

**Issue by berrytools** [microsoft/vscode-mssql#18317] opened 2024-10-25 10:46 UTC
Hi,
The new Rich Experiences is great milestone in mssql extenssion for vscode.
The only thing that is annoying for me is support of result set in Query Result pane.
Following cases are problematic for me:
1. Result Pane is only single pane and it is changing dynamicaly depending on what SQL script editor window you click. But when you want to work with one script and see results from another query, it's impossible.
2. When you are working on one script and another SQL script is runnung in the background the Query Result pane grabs cursor focus whenever result or message is updated in Query Result Pane - this is very annoying when you are typing code in editor.

So my ask for you is to enable possibility to have option to switch on/off this particular feature in extenssion configuration.
When the feature (Query Results in Query Results Pane) is disabled, the Query Results should be displayed as before enabling Rich Experiences.

BR
Kamil

**Comment by nbarnwell** [comment] 2024-10-25 11:31
I second this. The query results aspect of the new experience is actually not quite as good as the old one, I'm afraid.

**Comment by aasimkhan30** [comment] 2024-10-27 03:13
Possibly dup #18316

**Comment by Benjin** [comment] 2024-11-01 18:37
I'm closing this item as a duplicate of #18316.  The good news is that this is something we're working to bring back, hopefully in the very next release!

**Closed by Benjin** 2024-11-01 18:37 UTC
Labels: Enhancement, Area - Query Editor, Triage: Needed
