### ISSUE TITLE
Runaway memory usage

### ISSUE THREAD

**Issue by dsbert** [Microsoft/vscode-mssql#395] opened 2016-11-21 21:00 UTC
I had a very strange memory issue while using vs code with sql files open. I've not seen this issue happen before installing the mssql extension, but I'm not sure of the exact reason for it. The below steps are what I was able to recall happening.

- MSSQL Extension Version: 0.1.5
- VSCode Version: 1.7.1
- OS Version: Windows 7

Steps to Reproduce:

1. Have two .sql files open side-by-side, no active queries running
2. Edit and save file open in right pane
3. Using windows explorer, delete file in right pane
4. Using windows explorer, rename file in left pane to same name as previous file open in right pane
5. Attempt to close files in both panes

Result: Entire computer became unresponsive for several seconds. After that, Chrome tabs crashed with out of memory warnings. Checked Resource Monitor and found that sql tools was using over 6 GB of memory. After closing vs code, memory used by sql tools was released and system returned to normal.

Afterwards, I tried running a query using the mssql extension and the memory usage for 311,000 rows is minimal.

**Comment by kevcunnane** [comment] 2016-11-22 19:08
@benrr101 will be investigating this issue. He may have some questions if there are problems reproducing, but hopefully we can figure out if it's a problem in our extension or if this is a general issue for VSCode.

**Comment by benrr101** [comment] 2016-11-22 22:25
@dsbert this is a very interesting issue. So far I haven't been able to repro it on Windows 10 or OSX. My attempt to repro on Windows 7 has been inconclusive because I'm stuck waiting for a fresh SP1 install to update to the point that it will run the SQL tools service. I'll update once I get that repro completed.

However, in the meantime, I've done some experimentation and it looks like on OSX and Win10, you can't complete step 5 of your repro (close both panes). It would appear that on OSX and Win10, when the underlying files disappear (delete them, or rename them), the files are immediately closed in the VS Code instance. This doesn't trigger the runaway memory usage. I'll know more once I can get it running on Win7, but my initial thoughts are that this is an oddity with VS Code that's highlighting a bug in the SQL tools service.

**Comment by dsbert** [comment] 2016-11-23 03:48
@benrr101 I thought this issue might be difficult to reproduce. I run vs code on Windows 7, 10, and OSX. I think generally on windows 7, I've had mixed results when editing open files outside of vs code. Sometimes I am not notified of any changes until I attempt to save or close the file, other times I'm shown a warning that the file has changed. In this case, I believe I attempted to close both panes very quickly. Before any warnings were displayed, the program locked up.

**Comment by benrr101** [comment] 2016-11-23 23:01
@dsbert I did finally get a fully up-to-date Windows 7 machine running. Unfortunately, I still was not able to reproduce the issue even on the Windows 7 machine. If the files are opened from the open directory (ie, the tree of files on the left), the files are closed when they're deleted/renamed from explorer. If the files are opened without a directory open (dragged from explorer without a folder open), the files won't be closed when they're deleted/renamed. But, even so, I haven't been able to close the panes quick enough to get the runaway memory to reproduce.

 As such, I'd encourage you to double check that you've updated to the latest VS Code (1.7.2) and .NET core versions (1.1) as well as making sure all updates to Windows 7 have been installed. Since it seems the issue stems from the tools service expecting the files to be there when they don't exist, I'll make sure we add some tests to our code to validate expected behavior in these scenarios.

Again, thanks for reporting this issue, but it doesn't look actionable since I am unable to reproduce it.

**Closed** 2016-11-23 23:02 UTC
Labels: bug, important

**Comment by victorschinaider** [comment] 2017-08-02 12:16
I'm having the same problem in Ubuntu. After use the mssql extension, the pc totally freezes. Memory jump from 2 GB of consumption, to 7,5 GB.
