### ISSUE TITLE
SqlToolsServiceLayer pegging CPU

### ISSUE THREAD

**Issue by sixfeetover** [microsoft/vscode-mssql#968] opened 2017-08-02 14:42 UTC
- MSSQL Extension Version: 1.1.0
- VSCode Version: 1.14.2
- OS Version: macOS Sierra 10.12.6

SqlToolsServiceLayer is using a ton of CPU while I have idle connections open. I had four tabs open to two different sql servers. After sitting idle for a few moments, CPU spiked and remained high. Disconnecting had no effect - I had to close vscode entirely.

![screen shot 2017-08-02 at 10 34 45 am](https://user-images.githubusercontent.com/52384/28879025-f8444b3a-776e-11e7-9b33-aebd8c5c5931.png)

Steps to Reproduce:

1. Establish connection(s) to sql servers in vs-code
2. Wait

**Comment by kevcunnane** [comment] 2017-08-02 17:21
@benrr101 could you take a look at this? @sixfeetover does this reliably happen for you? We've had reports about this in the past but struggle to reproduce. If you're willing / able, any extra info you have would be great. Ben can give you details on what's most helpful.

**Comment by sixfeetover** [comment] 2017-08-02 20:41
I would be happy to do what I can to provide more information if I can figure out what to provide. For example, right now it's running at 97% CPU, but I used it for a few hours after submitting this issue at normal CPU levels. I'm having a hard time pinning down a pattern for when it spikes, but I am going to keep trying to observe (Is it on errors? info messages? stored procedures? ad hoc queries? etc).

**Comment by kevcunnane** [comment] 2017-08-18 20:52
We've had some reports of similar issues in latest SSMS release. We think something is going wrong in intellisense / SMO and are asking their help to investigate since any fix will be in that shared code. Will keep this thread updated once we know more.

**Closed** 2020-01-23 19:15 UTC
Labels: bug
