### ISSUE TITLE
add query plan viewer including an easy way to add missing indexes

### ISSUE THREAD

**Issue by npongo** [microsoft/vscode-mssql#17850] opened 2023-11-29 16:32 UTC
include a way to visualize execution plans and missing indexes much like MSSQL Management Studio.

**Comment by kburtram** [comment] 2024-08-21 18:46
Closing as duplicate of https://github.com/microsoft/vscode-mssql/issues/375.  We're working on adding this functionality in a future release.

**Closed by kburtram** 2024-08-21 18:46 UTC
Labels: Enhancement
