### ISSUE TITLE
Don't display release notes on every startup

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-mssql#1208] opened 2019-03-27 20:01 UTC
- MSSQL Extension Version: 1.5.0
- VSCode Version: 1.32.3 (1.32.3)
- OS Version: macOS

Showing a link to the release notes makes sense after the extension has been updated, but the 
release notes dialog shows up every time the extension is loaded, which I assume is not intended(?)

![](https://d.pr/i/1C6FBN+)

**Comment by kburtram** [comment] 2019-03-27 20:53
@fonnesbeck this is not the intended behavior.  You should only see that notification once after each time the extension is updated (we did recently push an update from v1.4 to v1.5).

I'm unable to repro this.  Are there any other repro steps that may help me diagnosis?

**Comment by kburtram** [comment] 2019-06-05 23:22
Closing as no repro.  Please add additional info if the issue persists.

**Closed by kburtram** 2019-06-05 23:22 UTC
Labels: bug, needs repro
