### ISSUE TITLE
Feature Request: authenticationType Integrated but different credentials

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-mssql#756] opened 2017-03-02 12:05 UTC
- MSSQL Extension Version: 0.2.1
- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/8189808/23506391/525d24c4-ff48-11e6-8a2c-492870bc8e04.png)

- OS Version: Windows 10

I often encounter a certain scenario where there is a SQL admin account which I need to use that differs from my current user but the SQL security is disabled.
So usually I would need to use mstsc to login with that user and then open the SQL Management Studio that also uses Windows Authentication.
So my request would be that I can also have either a username/password scenario for the integrated type or a different type that would use windows authentication for SQL integrated authentication.

**Comment by kevcunnane** [comment] 2017-03-03 21:29
Our best practice from SSMS is to follow the steps at https://wikidba.net/2015/07/07/connecting-sql-database-with-different-windows-credential-in-sql-server-management-studio-ssms/ and run as a different user. This should also work for VSCode. Could you try this out and let us know if it solves this issue for you?

**Comment by con-ssc** [comment] 2017-03-06 09:55
This might of course work. But it very much defeats the purpose. When I run VSCode as a different user, I also have a different usersettings as well es different extension setup. So in order to make this work I had to mirror everything to the other user.

**Comment by kevcunnane** [comment] 2017-03-07 01:15
I understand. This is a hard issue to solve at the tools level - we end up connecting through the ADO.Net stack (in the case of this extension, via .Net Core) so ultimately we can only do what that driver supports. I don't believe the SqlClient/ADO.Net stack supports this and that's going to block us from implementing this.

**Comment by cheenamalhotra** [comment] 2023-09-15 20:50
Closing as duplicate of https://github.com/microsoft/vscode-mssql/issues/826

**Closed by cheenamalhotra** 2023-09-15 20:50 UTC
Labels: Enhancement, Area - Connection
