### ISSUE TITLE
Notification "Testing connection profile..." when connecting to database

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#17514] opened 2023-01-11 17:56 UTC
- MSSQL Extension Version: 1.17
- VSCode Version: any
- OS Version: any

Steps to Reproduce:

1. Connect to a saved connection in OE tree with "Connect" link

Expected: Server connects and any notifications are relevant, such as "Connection error" or "Connecting...", etc.

Actual: Server connects and a notification "Testing connection profile".  This text seems obscure as it is unclear as to why there is a test required and why the user needs to be notified about this test.

![image](https://user-images.githubusercontent.com/599935/211881986-5b547fc0-794b-4a41-9b23-832563187f25.png)

**Comment by Charles-Gagnon** [comment] 2023-01-11 18:18
Duplicate of https://github.com/microsoft/vscode-mssql/issues/17431

**Closed by Charles-Gagnon** 2023-01-11 18:18 UTC
Labels: Bug, Area - Connection
