### ISSUE TITLE
Extension issue: this extension take a long time and don't implement.

### ISSUE THREAD

**Issue by EhmaedAlhams** [microsoft/vscode-mssql#17407] opened 2022-07-26 10:42 UTC
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.15.0`
- OS Version: `Windows_NT x64 10.0.25151`
- VS Code version: `1.69.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Charles-Gagnon** [comment] 2022-07-26 15:22
@EhmaedAlhams I'm closing this as a probable duplicate of https://github.com/microsoft/vscode-mssql/issues/17406, if you see this again please paste the content of your clipboard into that issue so we can see where the issue actually is.

**Closed by Charles-Gagnon** 2022-07-26 15:22 UTC
