### ISSUE TITLE
Constraints when going to a table definition

### ISSUE THREAD

**Issue by bergamin** [microsoft/vscode-mssql#759] opened 2017-03-02 19:36 UTC
- MSSQL Extension Version: 0.2.1
- VSCode Version: 1.10.1
- OS Version: Windows 7 SP1

When asking for the table definition it shows the CREATE TABLE script without constraints. It would be interesting to have the full table creation script being shown, so we could use it for helping on giving maintenance to the tables.

Thank you very much!

**Comment by kevcunnane** [comment] 2017-03-02 20:13
Thanks for this suggestion. This is definitely an interesting idea that we could look at. I suspect that SMO (which we currently use for scripting) has this as a configurable option, so we could look at implementing it. @sharonravindran what do you think?

**Comment by sharonravindran** [comment] 2017-03-07 01:57
Sure, we could show the constraints too. Today we display just the create script by design. I'll look at the other scripting options.

**Comment by kburtram** [comment] 2024-08-14 19:02
Closing this as "by design".  The Go to Definition/Peek Definition show just the CREATE TABLE statements, where the Script As Create command in Object Explorer shows the full CREATE TABLE with all the constraints.

**Closed by kburtram** 2024-08-14 19:02 UTC
Labels: Enhancement, Area - Query Editor
