### ISSUE TITLE
MSSQL: SQL Tools Service not starting on  latest VS Code Insider

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/vscode-mssql#718] opened 2017-02-23 19:33 UTC
- MSSQL Extension Version: 0.2.1
- VSCode Version: 1.10.0-insider 
- OS Version: Windows 10 Pro Insider Preview Build 15007.rs_prerelease.170107-1846

Steps to Reproduce:

1. Open VS Code in the SQL Script folder
2. Error  - mssql: SQL Tools Service component could not start.

FYI - This was working fine on previous VS Code Insider version. Now, it doesn't connect to my existing profiles.

![vscodeinsidermssql_error_2017-02-23_14-29-00](https://cloud.githubusercontent.com/assets/19892435/23275492/b40372ce-f9d4-11e6-977c-4b40afc3224f.jpg)

**Comment by MaximoTrinidad** [comment] 2017-02-23 23:37
Yes! I upgraded this morning the VS Code-Insider and MSSQL extension stopped working.  
:(

**Comment by kburtram** [comment] 2017-02-24 00:06
I'm seeing the same thing.  I'll investigate now and see what we need to do to roll-out a fix.

**Comment by kburtram** [comment] 2017-02-24 00:57
It looks like the uri format of the textDocument/didOpen message has a breaking change where it is now prefixed with "git:/".  Previously we where expecting this to be "file:/" and the new prefix isn't work with our file management code.  We'll follow-up with VS Code team to find out if the change is intentional and if we need to take a fix on our side.  The **bold** line in the payload below is causing the issue.


"textDocument/didOpen"

{ {
  "textDocument": {
   **"uri": "git:/d%3A/xplat/test/test3.sql",**
   "languageId": "sql",
   "version": 1,
   "text": ""
} } }

**Comment by kburtram** [comment] 2017-02-24 01:00
Here is the exception detail of the crash in SqlToolsService.  Basically System.Path.GetFullPath doesn't know how to resolve git:/ URIs.

{System.NotSupportedException: The given path's format is not supported.\r\n   at System.IO.Path.GetFullPath(String path)}

System.IO.Path.GetFullPath(string path) (\Unknown Source:0)
Microsoft.SqlTools.ServiceLayer.Workspace.Workspace.ResolveFilePath(string filePath) (d:\xplat\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\Workspace\Workspace.cs:112)
Microsoft.SqlTools.ServiceLayer.Workspace.Workspace.GetFileBuffer(string filePath, string initialBuffer) (d:\xplat\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\Workspace\Workspace.cs:160)
Microsoft.SqlTools.ServiceLayer.Workspace.WorkspaceService<Microsoft.SqlTools.ServiceLayer.SqlContext.SqlToolsSettings>.HandleDidOpenTextDocumentNotification(Microsoft.SqlTools.ServiceLayer.Workspace.Contracts.DidOpenTextDocumentNotification openParams, Microsoft.SqlTools.ServiceLayer.Hosting.Protocol.EventContext eventContext) (d:\xplat\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\Workspace\WorkspaceService.cs:248)
Microsoft.SqlTools.ServiceLayer.Hosting.Protocol.MessageDispatcher.SetEventHandler.AnonymousMethod__0(Microsoft.SqlTools.ServiceLayer.Hosting.Protocol.Contracts.Message eventMessage, Microsoft.SqlTools.ServiceLayer.Hosting.Protocol.MessageWriter messageWriter) (d:\xplat\sqltoolsservice\src\Microsoft.SqlTools.Hosting\Hosting\Protocol\MessageDispatcher.cs:176)
Microsoft.SqlTools.ServiceLayer.Hosting.Protocol.MessageDispatcher.DispatchMessage(Microsoft.SqlTools.ServiceLayer.Hosting.Protocol.Contracts.Message messageToDispatch, Microsoft.SqlTools.ServiceLayer.Hosting.Protocol.MessageWriter messageWriter)

**Comment by kburtram** [comment] 2017-02-24 01:08
I opened an issue with VS Code team to determine if this change is intentional.  If it is then we'll include this in our upcoming 0.3.0 release.

**Comment by MaximoTrinidad** [comment] 2017-02-24 01:39
Thanks everyone for the quick attention.  I had webinar yesterday where I was showing VS Code Insider working with MSSQL, Python, and PowerShell.  Unfortunately the bug stop me from showing the T-SQL piece.  But, eventually is going to get fix. Right!

Greatly Appreciate the efforts,

:)

**Comment by kburtram** [comment] 2017-02-24 01:56
There is a fix on our side to ignore the new git:/ events in our extensions service at https://github.com/Microsoft/sqltoolsservice/pull/254.  I'll wait to hear back on if this intended design change before merging.

**Comment by kevcunnane** [comment] 2017-02-24 02:29
@kburtram 's fix is merged and the tools service release is updated. Therefore re-downloading and uninstalling / reinstalling https://github.com/Microsoft/vscode-mssql/releases/download/v0.3.0/mssql-0.3.0.vsix should pull down a version with this fix.

I'll be updating the installers with an updated VSCode-MSSQL package shortly, or may just create a new 0.3.1 release to better capture this.

**Comment by kevcunnane** [comment] 2017-02-24 03:42
All binaries have been updated in the 0.3.0 candidate release. This now includes fixes for newline copy, this issue, and updated release notes

**Comment by MaximoTrinidad** [comment] 2017-02-24 15:10
@kburtram , @kevcunnane 

That's AWESOME! I'm looking forward to the next release of insider to test the changes.

Thanks again,
:)

**Comment by MaximoTrinidad** [comment] 2017-02-24 18:17
OK!  In my case, I proceed to download and install mssql-0.3.0.vsix.  
It's working now.

Good job!!
:)

**Comment by kburtram** [comment] 2017-02-24 18:28
@MaximoTrinidad  thanks for confirming!

**Comment by JudE2425** [comment] 2017-03-03 23:23
I'm still having a problem with this. Running Ubuntu Trusty. I was super excited to use Code to connect to my Azure SQL server without having to remote to my Win10 machine. I get the error as soon as I open an SQL file. After clearing that I enter my server details and it just spins without ever connecting or giving me an error message.

Has it been fixed already? I don't mind being patient, I just wanted to make sure that my problem wasn't something else.

Thanks!

**Comment by MaximoTrinidad** [comment] 2017-03-04 00:53
@JudE2425 

What's the extension version number?  My issue the SQL Tools Service got corrected by manually installing mssql-0.3.0.vsix.

Hope this helps,
:)

**Comment by JudE2425** [comment] 2017-03-04 00:57
strange. That's the extension number I have. I installed the azure extension pack, so I assume all of the dependencies came with it. Anyway, thanks for the heads up!

**Comment by MaximoTrinidad** [comment] 2017-03-04 01:09
Hey @JudE2425,

Hum! I'm curious!!  Have you tried to using only the mssql extension (by itself) and see if it connect without the Azure Extension.  There might be a chance these two extension may conflict each other.

:)

**Comment by JudE2425** [comment] 2017-03-04 01:15
That's a great idea! So I tried it. I uninstalled all of my extensions and then installed the MSSQL extension only. I then clicked on an .sql file and the terminal/debugger window popped up on the bottom. It said it was downloading some files and right before it says it was successful, the little error message pops up at the top and says that it was unable to start.

**Comment by MaximoTrinidad** [comment] 2017-03-04 01:33
Does by any change... did you recreated the profiles before trying it? In my case I had to recreate my SQL profiles. I'm just saying! It did help in my case. 
:)

**Comment by kevcunnane** [comment] 2017-03-04 01:55
@JudE2425 sorry to hear you're still having trouble. 

Perhaps we could help debug this to understand why it's failing? Steps that should help:
1. See if we get detailed log information: open user settings and add `"mssql.logDebugInfo": true,` so that we log as much as possible. Check out the SqlToolsService and MSSQL channels in the output window to see what information you get
2. Execute the `Toggle Developer Tools` option to open the Chrome debugger, go to the `Console` tab and see if there are relevant error messages logged
3. Advanced option if those doesn't give any useful information:
  - Clone this repository
  - Initialize and build: 
    - in the root directory, run `npm run install-packages` to pull down dependencies
    - run `gulp build` to build everything
    - run `code .` to start VSCode
  - Hit F5 to launch the debugger
    - Add a breakpoint in `serviceclient.ts`, line 85 (the `error` function).
    - You should be able to see the actual, raw error message returned over the LanguageService channel

**Comment by kevcunnane** [comment] 2017-03-04 01:57
One more thing: could it be this issue https://github.com/Microsoft/vscode-mssql/wiki/windows10-universal-c-runtime-requirement? We need the Universal-C runtime to work on earlier versions of Windows. By any chance is that causing this problem for you?

**Comment by MaximoTrinidad** [comment] 2017-03-04 02:07
Good point @kevcunnane!  

I'm on the latest WIndows 10 Insider build 15046.  And VS Code Insider ver. 1.11.0.
:)

**Comment by JudE2425** [comment] 2017-03-04 02:14
In reverse order, I'm running Ubuntu 14.04 in a chroot, so I sure hope it's not a windows issue :-P

Here is the output from SQL ToolsService:
'''
[Error - 7:03:21 PM] Connection to server is erroring. Shutting down server.
[Error - 7:03:21 PM] Connection to server is erroring. Shutting down server.
[Error - 7:03:21 PM] Connection to server is erroring. Shutting down server.
Failed to load /home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/sqltoolsservice/0.3.0.5/Ubuntu14/libcoreclr.so, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/sqltoolsservice/0.3.0.5/Ubuntu14/libcoreclr.so'
'''
Here is the output from the Developer Tools when I select an SQL file:
'''
extensionHost.ts:282 [Extension Host] TypeError: Cannot read property 'dispose' of null
    at LanguageClient.cleanUp (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:647:30)
    at LanguageClient.stop (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:621:14)
    at LanguageClient.handleConnectionError (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:882:18)
    at errorHandler (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:744:19)
    at /home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:47:42
    at CallbackList.invoke (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at writeErrorHandler (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/main.js:113:22)
    at CallbackList.invoke (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at StreamMessageWriter.AbstractMessageWriter.fireError (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/messageWriter.js:28:27)
    at Socket.<anonymous> (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/messageWriter.js:60:67)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:319:10)
    at onwrite (_stream_writable.js:337:5)d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
3messageService.ts:126 mssql: SQL Tools Service component could not start.e.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:64n.Class.derive._oncancel @ winjs.base.raw.js:1641t.showMessage @ mainThreadMessageService.ts:34t.$showMessage @ mainThreadMessageService.ts:28e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
'''

Thanks so much for taking time out of your evening to help me. I really appreciate it.

Zack

**Comment by JudE2425** [comment] 2017-03-04 02:17
Oh, there was one more message I forgot to paste in. I apologize.
```
messageService.ts:126 mssql: SQL Tools Service component could not start.e.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:64n.Class.derive._oncancel @ winjs.base.raw.js:1641t.showMessage @ mainThreadMessageService.ts:34t.$showMessage @ mainThreadMessageService.ts:28e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:282 [Extension Host] ApplicationInsights:Sender [Object]
```
This was also in the developer tools output.

**Comment by kevcunnane** [comment] 2017-03-04 02:25
So the issue is definitely this:
```
Failed to load /home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/sqltoolsservice/0.3.0.5/Ubuntu14/libcoreclr.so, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/sqltoolsservice/0.3.0.5/Ubuntu14/libcoreclr.so'
```
Does this file exist at the specified location? I just downloaded the Ubuntu 14 package we're using (https://github.com/Microsoft/sqltoolsservice/releases/download/v0.3.0.5/microsoft.sqltools.servicelayer-ubuntu14-x64-netcoreapp1.0.tar.gz), unpackage and verified it is there. Can you try re-downloading (delete the sqltoolsservice directory and restart VSCode) and see if it "just works"? If the file is there, I'm not sure what might be going wrong, will need to dig in a bit more

**Comment by JudE2425** [comment] 2017-03-04 02:33
So, yes, the file existed. It was 8.1MiB.

I deleted the directory you said and it re-downloaded as soon as I restarted VS Code, then I got the following error:
```
extensionHost.ts:282 [Extension Host] TypeError: Cannot read property 'dispose' of null
    at LanguageClient.cleanUp (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:647:30)
    at LanguageClient.stop (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:621:14)
    at LanguageClient.handleConnectionError (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:882:18)
    at errorHandler (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:744:19)
    at /home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:47:42
    at CallbackList.invoke (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at writeErrorHandler (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/main.js:113:22)
    at CallbackList.invoke (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at StreamMessageWriter.AbstractMessageWriter.fireError (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/messageWriter.js:28:27)
    at Socket.<anonymous> (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/messageWriter.js:60:67)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:319:10)
    at onwrite (_stream_writable.js:337:5)d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
3messageService.ts:126 mssql: SQL Tools Service component could not start.e.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:64n.Class.derive._oncancel @ winjs.base.raw.js:1641t.showMessage @ mainThreadMessageService.ts:34t.$showMessage @ mainThreadMessageService.ts:28e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

**Comment by MaximoTrinidad** [comment] 2017-03-04 02:33
OK!  So, I just tested mssql on my Linux Ubuntu 16.04.1 and VS Code 1.10.0 with no issues with the SQL Tool Service.  Of course, I would also suggest to occasionally do a:

sudo apt update

and, if there are upgrade needed then do a:

sudo apt upgrade

Hope you get it corrected!
:)

This will also help to keep the OS up-to-date.

**Comment by JudE2425** [comment] 2017-03-04 02:57
So, yes, the file existed. It was 8.1MiB.

I deleted the directory you said and it re-downloaded as soon as I restarted VS Code, then I got the following error:
```
extensionHost.ts:282 [Extension Host] TypeError: Cannot read property 'dispose' of null
    at LanguageClient.cleanUp (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:647:30)
    at LanguageClient.stop (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:621:14)
    at LanguageClient.handleConnectionError (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:882:18)
    at errorHandler (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:744:19)
    at /home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:47:42
    at CallbackList.invoke (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at writeErrorHandler (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/main.js:113:22)
    at CallbackList.invoke (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at StreamMessageWriter.AbstractMessageWriter.fireError (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/messageWriter.js:28:27)
    at Socket.<anonymous> (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/messageWriter.js:60:67)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:319:10)
    at onwrite (_stream_writable.js:337:5)d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
3messageService.ts:126 mssql: SQL Tools Service component could not start.e.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:64n.Class.derive._oncancel @ winjs.base.raw.js:1641t.showMessage @ mainThreadMessageService.ts:34t.$showMessage @ mainThreadMessageService.ts:28e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

Then I uninstalled the whole program, deleted the .vscode directory, and then reinstalled from the channel instead of the .deb.

I opened a .sql file, installed only the mssql extension (as it was recommended by the software and it still failed to initialize after downloading the package again.

```
extensionHost.ts:282[Extension Host] TypeError: Cannot read property 'dispose' of null
    at LanguageClient.cleanUp (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:647:30)
    at LanguageClient.stop (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:621:14)
    at LanguageClient.handleConnectionError (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:882:18)
    at errorHandler (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:744:19)
    at /home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-languageclient/lib/main.js:47:42
    at CallbackList.invoke (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at writeErrorHandler (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/main.js:113:22)
    at CallbackList.invoke (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at StreamMessageWriter.AbstractMessageWriter.fireError (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/messageWriter.js:28:27)
    at Socket.<anonymous> (/home/zackskrip/.vscode/extensions/ms-mssql.mssql-0.3.0/node_modules/vscode-jsonrpc/lib/messageWriter.js:60:67)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:319:10)
    at onwrite (_stream_writable.js:337:5)
```

Thanks so much for your help. I'm going to bed. Have a good weekend!

**Comment by MaximoTrinidad** [comment] 2017-03-04 04:41
Hi @kevcunnane / @JudE2425 

Apparently there's a possible bug.

I had mssql extension (version 0.3.0) working on VS Code Insider 1.10.0 on my Linux machine working fine.  But, I proceeded to update to VS  Code to version 1.11.0 and now I'm getting an error: "Unable to execute the command while the extension is initializing".

And, it's worse!  I can't uninstalled any of my existing extensions. Clicking on the "uninstall" won't do anything. I can only to disable/enable but it won't clear the issue.

The SqlToolsService is hung up trying to initialize the service.  No debug error message is generated.

I'm on Linux Ubuntu 16.04.1, VS Code 1.11.0. 

Thanks,
:(

**Comment by kevcunnane** [comment] 2017-03-04 16:21
@MaximoTrinidad I think this is a VSCode Insiders build issue. I just updated to 1.11.0-insiders and after a few restarts, it now says my VSCode instance appears to be corrupt.If you can verify things still work OK on the standard VSCode install, I would recommend opening an issue against VSCode (https://github.com/Microsoft/vscode/issues). They are generally very good about fixing quickly.

**Comment by MaximoTrinidad** [comment] 2017-03-04 19:39
Thanks @kevcunnane!  I will post this on the VS Code side.
:)

**Comment by MaximoTrinidad** [comment] 2017-03-04 20:07
Hi @kevcunnane,

Just installed VS Code (not Insider) ver 1.10.0 and all the extensions works fine including mssql.

:)

**Comment by Nekronek0** [comment] 2017-04-03 11:01
Same errors here on Debian Stretch:
Failed to initialize CoreCLR, HRESULT: 0x80131500, corresponding to https://github.com/dotnet/cli/issues/2018.
Installing libicu52 solves the error

**Comment by thiagoabreu** [comment] 2017-04-17 15:27
Had the same issue in elementary OS 0.4

```
[Error - 7:03:21 PM] Connection to server is erroring. Shutting down server.
[Error - 7:03:21 PM] Connection to server is erroring. Shutting down server.
[Error - 7:03:21 PM] Connection to server is erroring. Shutting down server.
Failed to load /home/jedi/.vscode/extensions/ms-mssql.mssql-0.3.0/sqltoolsservice/0.3.0.5/Ubuntu16/libcoreclr.so, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/jedi/.vscode/extensions/ms-mssql.mssql-0.3.0/sqltoolsservice/0.3.0.5/Ubuntu16/libcoreclr.so'
```
I figured that it wasn't the `libcoreclr.so` file that was missing, but the `libunwind.so.8`. So I installed the package `libunwind8-dev` and it's working fine now.

**Comment by MaximoTrinidad** [comment] 2017-04-17 15:38
Thanks @thiagoabreu!  I will try this tonight when I get home.

By the way, I got side track on this one as the only problem still is with my Code Insider version on my main Linux system.  I can't seem to uninstall the application.

Can some help (or explain) how to completely remove the application? 

I tried everything I know.  I tried the Ubuntu App, dpkg remove, and even search then "Move to Trash".  Apparently, the application still stays loaded somewhere.  

Every time I install, what I think is a refresh application, it comes back with all of my previously installed extensions.  I think somehow the installation got corrupted as I'm able to successfully install on a clean Linux VM.

So, what are the proper  way to uninstall to do a clean installation?

Thanks,
Max

**Comment by thiagoabreu** [comment] 2017-04-18 16:33
@MaximoTrinidad Have you tried to delete the `~/.vscode/` and `~/.vscode-insiders/` folders?

**Comment by dzsquared** [comment] 2017-04-20 00:49
I was having similar issues to @JudE2425 with the SQL tools service not starting in a chroot with Ubuntu 16 - the resolution was as @thiagoabreu suggested - installing libunwind8-dev.

`sudo apt install libunwind8-dev`

**Comment by kburtram** [comment] 2017-04-24 21:37
@kevcunnane could you please confirm if there is anything we can do for this issue in the upcoming release?

**Comment by asmyers** [comment] 2017-04-25 18:19
Also effects Ubuntu 17.04  Not sure if this is relevant but it appears to be downloading a tarbal for Debian?  It goes into the Debian directory under the extension but with 16.10 it was going into an Ubuntu16 directory.

```
Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.


Platform: linux, x86_64, name=ubuntu, version=17.04 (Debian)

Installing SQL tools service to /home/icarus/.vscode/extensions/ms-mssql.mssql-0.3.0/sqltoolsservice/0.3.0.5/Debian.
Downloading https://download.microsoft.com/download/A/A/2/AA22B2D6-94D8-4C82-A388-D0246F567BBF/microsoft.sqltools.servicelayer-debian-x64-netcoreapp1.0.tar.gz
(24532 KB) .................... Done!
Installing ...
Done! 157 files unpacked.

```

**Comment by kburtram** [comment] 2017-05-02 00:24
The Ubuntu 17.04 issue appears to be an issue with .Net Core 1.0.  We're following up on how best to support this more recent distro, but we don't have a fix currently available.

I'm going to clear the GA milestone and we'll need to fix in the next release or hotfix.  I'll add a comment to the known issue list.

**Comment by basabuber** [comment] 2017-05-28 02:16
Just fyi, latest release .Net Core seems to work fine (for me) on Ubuntu 17.04.

**Comment by ed-alertedh** [comment] 2017-06-08 04:47
@basabuber Could you please share what versions of VS Code / vscode-mssql / dotnet core you're having success with?

I'm experiencing this issue on Ubuntu 17.04 with VS Code 1.12.2 / vscode-mssql / dotnet 2.0.0-preview2-006127

**Comment by kburtram** [comment] 2017-06-08 07:09
@ed-alertedh @basabuber the current extension is built using .Net Core 1 which doesn't support Ubuntu 17.04.  We'll be upgrading to .Net Core 2 in the next release.  

I've posted an early test build based on .Net Core 2 at https://github.com/Microsoft/vscode-mssql/releases/tag/v1.0.0-alpha.10 that can be side-loaded into VS Code using the Install From VSIX option.  The build has a couple known issues we'll be fixing in the next week or so, but should be mostly stable.  It would be great if you can give it a try and let me know if you hit any issues.

**Comment by MaximoTrinidad** [comment] 2017-06-08 10:43
@kburtram,

That's Awesome!!  I'll give it try when I get a chance and let you know if anything is going on.

Thanks,
:)

**Comment by mkurz** [comment] 2017-06-08 10:53
@kburtram The alpha version with .Net Core 2 support finally works for me! Thank you! :+1:  (I am using Ubuntu 16.10)

**Comment by asmyers** [comment] 2017-06-08 11:54
@kburtram The alpha version also works for me on Ubuntu 17.04!  Thanks! :+1:

**Comment by ed-alertedh** [comment] 2017-06-09 01:07
@kburtram Yep, that's working for me too, thanks!

As an aside, I'm still a little curious about the whole system of bundling a runtime with the sql service. Isn't the whole point of .NET that the code targets a certain framework and is decoupled from the runtime/host platform?

**Comment by gavincampbell** [comment] 2017-06-16 20:18
Fixed for me too on Fedora 25, VS Code 1.13. Prior to taking the update I couldn't connect to a SQL instance in a local VM (with 1433 forwarded), even though sqlcmd could connect OK. I also got that "extension failed to load message >50% of the time when setting file type to SQL.

**Comment by kevcunnane** [comment] 2017-07-19 15:53
I'll close this out as this version is now supported in the latest full release.

**Closed by kevcunnane** 2017-07-19 15:53 UTC
Labels: bug, customer issue, important

**Comment by aliasadidev** [comment] 2020-11-18 13:14
I've  had the same issue in Ubuntu 20.04, I downloaded the latest version of  SQLToolsService at [download sqltoolsservice](https://github.com/microsoft/sqltoolsservice/releases) and then exteracted the file to "/home/user/.vscode/extensions/ms-mssql.mssql-1.9.0/sqltoolsservice/1.9.0/Ubuntu16/"
