### ISSUE TITLE
host_name() in SQL Server Vnext in Visual Studio Code returns NULL

### ISSUE THREAD

**Issue by kannankandasamy** [Microsoft/vscode-mssql#853] opened 2017-05-01 20:16 UTC
VSCode Version: 1.11
OS Version: Windows 10
I am using SQL Server Vnext CTP 2.0 on Windows 10.

SELECT host_name()

function returns null if I use "Visual Studio Code" as client whereas it returns correct server name if I use SQL Server Management Studio 17 for SQL Server 2017.

FYI..

SELECT @@SERVERNAME

Returns correct instance name in Visual Studio Code.

Steps to Reproduce:

Install SQL Server Vnext CTP 2.0
Install Visual Studio Code
Connect SQL Server using Visual Studio Code on SQL login
Run above "SELECT host_name()" query

**Comment by benrr101** [comment] 2017-05-01 20:20
Hi @kannankandasamy, thanks for your feedback! This issue is already tracked in this issue https://github.com/Microsoft/vscode-mssql/issues/602

To sum it up: The issue is actually a bug in .NET Core and should be addressed in .NET Core 2.0. Upgrading to .NET Core 2.0 is a high priority for us in the next month+.

Since this is a duplicate, I'll close it, but if the issue I linked doesn't match what you're experiencing, reply back and we can reopen.

**Closed by benrr101** 2017-05-01 20:20 UTC
