### ISSUE TITLE
Add language configuration to  syntaxes/sql.configuration.json

### ISSUE THREAD

**Issue by CoenraadS** [microsoft/vscode-mssql#1182] opened 2019-01-16 19:45 UTC
- MSSQL Extension Version: `.4.0
- VSCode Version: 1.30.1
- OS Version: Windows 10

Hello

This extension defines its language configuration programmatically. 

https://github.com/Microsoft/vscode-mssql/commit/bbd2d5986fba1822c7670dd45da23d6b951c16a8

I am requesting to restore the settings into `syntaxes/sql.configuration.json` file, so that other extensions can read this extensions language settings.

The reason for this request is: https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues/50 

My extension requires reading other extensions language settings and currently cannot color SQL when this extension is enabled.

**Comment by kburtram** [comment] 2024-08-16 02:11
The configuration was moved from the JSON file to programmatic declaration to fix bug https://github.com/microsoft/vscode-mssql/issues/277.  Closing as "By Design" but we'd be happy to consider a PR to move these settings to config file if the previous bug could be addressed.

**Closed by kburtram** 2024-08-16 02:11 UTC
Labels: Enhancement, Area - Query Editor, Area - Language Service
