### ISSUE TITLE
Feature request: option to default to None for SQL handler

### ISSUE THREAD

**Issue by eksortso** [microsoft/vscode-mssql#1749] opened 2020-09-16 17:56 UTC
This is a request to add an option that would allow the default handler for new and opened `SQL` files to be none.

I work with several different flavors of SQL, including SQL Server, and this extension is still useful for working with the others that a deal with on a regular basis. However, I always have to use `mssql.chooseLanguageFlavor` to turn off the errors when I work with a different flavor of SQL. I have key bindings to speed this up, but I'd like to request an option to have the SQL Language default be None instead of MSSQL.

My current configuration:
- MSSQL Extension Version: 1.9.0
- VSCode Version: 1.49.0 (user setup)
- OS Version: Windows_NT x64 10.0.18362

**Comment by eksortso** [comment] 2021-06-21 22:10
I've discovered a setting that does basically the same thing. It may be overkill, especially if you have some SQL files worth checking and some that are not.

```json
    "mssql.intelliSense.enableErrorChecking": false
```

I'll keep the ticket open. The above works in my case but won't work for everyone.

Latest configuration:

* MSSQL Extension Version: 1.10.1
* VSCode Version: 1.57.1 (user setup)
* OS Version: Windows_NT x64 10.0.19042

**Comment by Benjin** [comment] 2024-11-08 15:52
Duplicate of #17298.  I'm going to keep the other issue because it's been used for tracking this issue more recently.

**Closed by Benjin** 2024-11-08 15:52 UTC
Labels: Enhancement, Area - Query Editor
