### ISSUE TITLE
mssql: SQL Tools Service component could not start.

### ISSUE THREAD

**Issue by jdw101** [Microsoft/vscode-mssql#419] opened 2016-11-27 23:31 UTC
- MSSQL Extension Version: 0.15
- VSCode Version: 1.72
- OS Version: Ubuntu 11.10

Steps to Reproduce:

1.  Run VSCode with the mssql extension installed using --verbose (fails either way but verbose is how I get the error to be more interesting!)

[3778:1127/182125:INFO:CONSOLE(90)] "mssql: SQL Tools Service component could not start.", source: file:////home/jwilliams/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (90)
[3778:1127/182126:INFO:CONSOLE(121)] "%c[Extension Host]", source: file:////home/jwilliams/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (121)
[3778:1127/182126:INFO:CONSOLE(121)] "%c[Extension Host]", source: file:////home/jwilliams/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (121)
[3778:1127/182126:INFO:CONSOLE(90)] "mssql: SQL Tools Service component could not start.", source: file:////home/jwilliams/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (90)
[3778:1127/182126:INFO:CONSOLE(90)] "mssql: SQL Tools Service component could not start.", source: file:////home/jwilliams/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (90)

**Comment by jdw101** [comment] 2016-11-27 23:33
Please let me know if there is some way to debug this, I have sql server running and the tools sqlcommand, odbc and bcp all working (tested) Also tested that I can connect to the running instance from SSMS outside (not that it matters for this problem but maybe?)  I've blown away the install and untarred it again in a new directory and run as a different user.

**Comment by jdw101** [comment] 2016-11-27 23:36
Full output 


7ba55c5860b152d999dda59393ca3ebeb1b5c85f
jwilliams@cg-dev-lx-02:~/Downloads/VSCode-linux-x64/bin$ ./code --verbose &
[1] 4274
jwilliams@cg-dev-lx-02:~/Downloads/VSCode-linux-x64/bin$ [4284:1127/183553:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[4284:1127/183553:ERROR:browser_main_loop.cc(261)] GTK theme error: Unable to locate theme engine in module_path: "adwaita",
[4284:1127/183553:ERROR:browser_main_loop.cc(261)] GTK theme error: Unable to locate theme engine in module_path: "adwaita",
[4304:1127/183554:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 6:35:54 PM] Starting VS Code in verbose mode
[main 6:35:54 PM] from: /home/jwilliams/Downloads/VSCode-linux-x64/resources/app
[main 6:35:54 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[main 6:35:55 PM] IPC#vscode:startCrashReporter
[main 6:35:55 PM] IPC#vscode:setHeaders
[main 6:35:56 PM] IPC#vscode-workbenchLoaded
[4284:1127/183556:INFO:CONSOLE(90)] "mssql: SQL Tools Service component could not start.", source: file:////home/jwilliams/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (90)
[4284:1127/183556:INFO:CONSOLE(121)] "%c[Extension Host]", source: file:////home/jwilliams/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (121)
[4284:1127/183556:INFO:CONSOLE(121)] "%c[Extension Host]", source: file:////home/jwilliams/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (121)
[4284:1127/183556:INFO:CONSOLE(90)] "mssql: SQL Tools Service component could not start.", source: file:////home/jwilliams/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (90)
[4284:1127/183556:INFO:CONSOLE(90)] "mssql: SQL Tools Service component could not start.", source: file:////home/jwilliams/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (90)



And from the VSSCode UI

[Error - 6:35:56 PM] Connection to server is erroring. Shutting down server.
[Error - 6:35:56 PM] Connection to server is erroring. Shutting down server.
[Error - 6:35:56 PM] Connection to server is erroring. Shutting down server.
Failed to initialize CoreCLR, HRESULT: 0x80131500

**Comment by jdw101** [comment] 2016-11-28 00:00
Added the following per the other thread, no logging data showed up however



@eugeneduvenage this message is the generic "out-of-process component" crashed error.

Could you please configure the user setting "mssql.logDebugInfo": true? This will cause the out-of-proc service to create a debug log which will hopefully contain the crashing exeception. The log should be in the ~/.vscode/extensions/ms-mssql.mssql/sqltoolsservice/0.1.2/Ubuntu16/ directory. If there is an error or exception messages in the log could you please provide it?

**Comment by kevcunnane** [comment] 2016-11-30 00:27
Hi, the issue here is that Ubuntu 11.0 is not one of the supported operating systems - see our list at https://github.com/Microsoft/vscode-mssql/wiki/operating-systems. 
To resolve this, is it possible to update your machine to use Ubuntu 14.04 or 16.04?

The root cause is that a lot of our code is built on .Net Core, which is only available for a fixed set of distributions. Note that we've worked to address the poor error message and make it clear when a distro is not supported - #400 is the fix for this and is in our most recent nightly release.

**Comment by dudanogueira** [comment] 2016-12-13 20:45
Hi there! Had the same problem and added 

return Platform.Ubuntu16;

right above the "switch(id){" line.

It's now working under Linux Mint 18.

Will test it against a test MSSQL later. THanks!!!

> const id = getValue('ID');
        return Platform.Ubuntu16;
        switch (id) {

**Comment by notalklu** [comment] 2017-01-03 00:45
MSSQL Extension Version: 0.2.0
VSCode Version: 1.8.1
OS Version: Windows 8.1
I have the same problem.And I have tried to install the pre-req follow the instruction https://github.com/Microsoft/vscode-mssql/wiki/windows10-universal-c-runtime-requirement.
But I can't install the tools successfully.
And i have set "mssql.logDebugInfo": true. Where can i get the debug log in windows 8.1?

**Comment by llali** [comment] 2017-01-03 17:20
@notalklu you should be able to see the debug logs for installing the service in the output window, "SqlToolsService initializing" channel

**Comment by notalklu** [comment] 2017-01-05 01:39
@llali Thanks. And the output of the "SqlToolsSerivce initializing" are 
"Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

Platform: win32, x86_64 (Windows)"

**Comment by llali** [comment] 2017-01-05 17:26
@notalklu this means your service is already installed. There shouldbe a message to say service is initialized and that's an issue but they shouldn't be any problem with the service. Do you get any error in the extension that service is not activated or have you tried making a connection and didn't work?

**Comment by notalklu** [comment] 2017-01-06 06:40
@llali 
![vscode1](https://cloud.githubusercontent.com/assets/10054253/21709674/ef2595a8-d41d-11e6-94f2-3665158634dc.png)
![vscode2](https://cloud.githubusercontent.com/assets/10054253/21709679/f6c46258-d41d-11e6-8d69-e22b6ee48b0c.png)

**Comment by llali** [comment] 2017-01-06 17:20
@notalklu So there's a problem with running the service and unfortunately the error is not logged anywhere. What we can do to troubleshoot is to run the service manually to see the actual error. Please run the following exe on command prompt:
%USERPROFILE%.vscode\extensions\ms-mssql.mssql-0.2.0\sqltoolsservice\0.2.0\Windows\Microsoft.SqlTools.ServiceLayer.exe

**Comment by kburtram** [comment] 2017-04-24 20:30
I'm going to close this issue since there hasn't been any recent activity, and we've had a couple public releases since the previous comment.  If this is still an issue please reactive so we can investigate.

**Closed by kburtram** 2017-04-24 20:30 UTC
Labels: bug, customer issue, freeze-slow-crash

**Comment by mkurz** [comment] 2017-06-08 10:57
You may want to try the latest alpha which includes .Net Core 2, it may fixes your issues:
https://github.com/Microsoft/vscode-mssql/issues/718#issuecomment-307018770: 
(Works for me)
