### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by bernatrm** [microsoft/vscode-mssql#17094] opened 2021-11-08 15:58 UTC
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.11.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.62.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Charles-Gagnon** [comment] 2021-11-08 16:54
I'm closing this due to lack of information - please make a new issue with a description of the issue and anything else you may have to help us figure out what the problem is!

**Closed by Charles-Gagnon** 2021-11-08 16:54 UTC
