### ISSUE TITLE
Large result sets cannot be exported to Excel

### ISSUE THREAD

**Issue by GrantQuick** [microsoft/vscode-mssql#1058] opened 2018-02-02 09:48 UTC
- MSSQL Extension Version: 1.3.0
- VSCode Version: 1.19.3
- OS Version: Windows 10 v1709 (OS Build 16299.192)

Steps to Reproduce:

1. (example) Select top 100,000 rows from a table containing postal address data (or any other query that returns a significant amount of data. Run query.
2. Click Save as Excel icon.
3. Error message appears: 
`mssql: Failed to save results. Failed to save test.xlsx: The Writer is closed or in error state.`
4. test.xlsx is created, but cannot be opened by Excel and the file cannot be deleted until VS Code has been closed.

The Save as Excel function works perfectly for smaller result sets (eg select top 10,000).

**Comment by martix1980** [comment] 2018-03-02 09:35
the same pb withe 2031 rows.

MSSQL Extension Version: 1.3.0
VSCode Version: 1.20.1
OS Version: Windows 10 v1709 (OS Build 16299.248)

**Comment by lemol** [comment] 2019-10-21 16:37
I can export large result (> 100,000) to Excel, but I get this error message when there is some kind of special characteres in the result.

E.g.: try to export result with the following text: "V TR"

MSSQL Extension Version: 1.7.0
VSCode Version: 1.38.1
OS Version: Windows 8.1

**Comment by dbrocha** [comment] 2020-10-12 14:55
Same issue here -- agreed it is special characters causing the error.

**Comment by janborup** [comment] 2021-05-13 17:52
I have this issue with just a couple of rows.
The the issue is that some data contains special chars in the SQL dataset lige a CHAR(2), and this result in the error.

MSSQL Extension Version: 1.10.1
VSCode Version: 1.56.2
OS Version: Windows 10 (19042.982)

**Comment by alanrenmsft** [comment] 2021-12-03 01:16
I tried the string 'V→TR' mentioned in https://github.com/microsoft/vscode-mssql/issues/1058#issuecomment-544600271, and also used other special characters and characters in other languages, but not able to reproduce the issue.

could someone please share the strings that could reproduce the issue?

**Comment by kburtram** [comment] 2024-08-15 18:49
Closing older issues with pending "Needs More Info" requests.

**Closed by kburtram** 2024-08-15 18:49 UTC
Labels: Bug, Needs More Info, Area - Query Editor, Area - Performance
