### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Scatterblak** [microsoft/vscode-mssql#17435] opened 2022-09-05 05:07 UTC
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.16.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.71.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 668,
		"activateCallTime": 0,
		"activateResolvedTime": 7589,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-mssql.mssql",
				"_lower": "ms-mssql.mssql"
			},
			"activationEvent": "onLanguage:sql"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```
This thing is a tragedy. It works for 5 minutes, then hangs, and takes everything with it.

**Comment by kburtram** [comment] 2024-08-16 18:04
Duplicate of https://github.com/microsoft/vscode-mssql/issues/17436

**Closed by kburtram** 2024-08-16 18:04 UTC
