### ISSUE TITLE
Connection config pulling from wrong settings file

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/vscode-mssql#452] opened 2016-12-03 22:49 UTC
- MSSQL Extension Version: dev branch
- VSCode Version: Insiders
- OS Version: Windows

If you have vscode insiders and vscode installed, the config directory can be wrong and be referring to the wrong settings file.

![image](https://cloud.githubusercontent.com/assets/4324725/20862717/6b93c3de-b967-11e6-9ec7-25d576db16a0.png)

In the image you can see that it is pointing towards the public code user profile settings file when I am in the insiders build. So instead of `..../Roaming/code` it should be `.../Roaming/Code - Insiders`.

However, using the getConfiguration vscode api pulls from the proper settings file.

**Comment by kevcunnane** [comment] 2016-12-05 18:32
Duplicate of #242 - closing

**Closed by kevcunnane** 2016-12-05 18:32 UTC
Labels: bug
