### ISSUE TITLE
Backslash character last in string breaks syntax highlighting

### ISSUE THREAD

**Issue by johanrex** [microsoft/vscode-mssql#1700] opened 2020-06-22 13:21 UTC
- MSSQL Extension Version:
v1.9.0

- VSCode Version:
1.46.1

- OS Version:
Windows 10

Steps to Reproduce:

1. Paste this text in an sql file:
```
select 'syntax highlighting works fine if the \ character is not last'
select 'syntax highlighting breaks if the \ character is last, like this\'
select 'syntax highlighting is now broken.'
```
Picture of problem:
![bild](https://user-images.githubusercontent.com/6969298/85292213-db46c400-b49b-11ea-88e8-3462b6617963.png)

For reference, here's the correct syntax highlighting as rendered by SSMS. 
![bild](https://user-images.githubusercontent.com/6969298/85369555-93707d00-b52d-11ea-97f6-ab3ac5f99492.png)

**Comment by SJMakin** [comment] 2020-06-25 18:20
Duplicate of #1680

**Comment by abist** [comment] 2020-10-12 17:31
Fixed by https://github.com/microsoft/vscode-mssql/pull/1701

**Closed by abist** 2020-10-12 17:31 UTC
Labels: bug
