### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by art2003** [Microsoft/vscode-mssql#1202] opened 2019-03-26 14:18 UTC
- Issue Type: `Performance`
- Extension Name: `mssql`
- Extension Version: `1.4.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/akarapetyan/ms-mssql.mssql-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kburtram** [comment] 2019-03-26 20:36
Looks like a duplicate of https://github.com/Microsoft/vscode-mssql/issues/1188.  Please attach the performance log mentioned in the bug report text (`/Users/akarapetyan/ms-mssql.mssql-unresponsive.cpuprofile.txt`) and I'll take a look.

**Closed by kburtram** 2019-03-26 20:36 UTC
