### ISSUE TITLE
Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'

### ISSUE THREAD

**Issue by jorys** [Microsoft/vscode-mssql#778] opened 2017-03-15 14:34 UTC
- MSSQL Extension Version:0.3.0
- VSCode Version:1.10.2
- OS Version: Windows 8.1 Enterprise

Steps to Reproduce:

1. "authenticationType": "Integrated"
2. Select on a different instance (sys.servers), I got that message : Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'. 

Thanks for your help.

**Comment by kevcunnane** [comment] 2017-03-16 01:32
@jorys - could you provide some more information? When you say "Select on a different instance (sys.servers)" what do you mean?
- Are you connected to a server using the connection profile?
- Is this a query against a linked server?
- Does this only happen in the VSCode extension, or does the same problem happen in SSMS/SSDT?

I'm asking the last question in particular since this sounds like it might be an issue with one server trying to connect to another one, and the Network Service account not being setup correctly for this. In which case, the solution would be on the Server configuration side rather than the extension. Thanks!

**Comment by jorys** [comment] 2017-03-16 08:41
Hello,

I tried a query on another table, MSSQL works perfectly!
For my problem query, I get a better message on SSMS: 
> XML data type not supported in Distributed Queries

So my problem is in the definition of the table.
Thanks for your help.

**Comment by kevcunnane** [comment] 2017-03-16 17:24
OK - I'll close this issue in that case. One thing is that if the error message is consistently different, it might be worth opening this as an issue against https://github.com/dotnet/corefx as this could be a regression (e.g. message handling isn't as good there as in .Net Framework).

**Closed by kevcunnane** 2017-03-16 17:24 UTC
Labels: bug, customer issue
