### ISSUE TITLE
Please add option to output as text

### ISSUE THREAD

**Issue by taranttini** [microsoft/vscode-mssql#642] opened 2017-01-24 19:18 UTC
Every time I run sp_helptext, the query result has added many blank lines, so I copy the result, the copy has more blank lines between the grid result lines,

 If you add option of result as text, this problem I believe it is solved.

Thanks for attention

**Comment by PierreRossouw** [comment] 2017-02-02 20:19
I believe the next version of vscode-mssql has a setting for removing the extra newlines when copying from the grid, which should also solve your problem?

.vscode/settings.json

"mssql.copyRemoveNewLine" : true

**Comment by taranttini** [comment] 2017-02-02 20:35
So thanks,

**Comment by abist** [comment] 2020-03-06 00:43
Closing this as duplicate of https://github.com/microsoft/vscode-mssql/issues/1030. Please refer to this issue for tracking the feature.

**Closed by abist** 2020-03-06 00:43 UTC
Labels: backlog, enhancement
