### ISSUE TITLE
1.5.0  Install/Connect problems

### ISSUE THREAD

**Issue by nickbunyan** [microsoft/vscode-mssql#1201] opened 2019-03-26 11:12 UTC
Issue Type: <b>Bug</b>

Having run 1.4 successfully for months, I attempted to update to 1.5. After an extremely long processing time it claimed to have installed correctly.
On restarting VSCode, everything looked OK but the content of the sqltoolsservice sub-directory was missing.  Further investigation showed an error message during the post-install processing which failed on the download of the following file:

Microsoft.SqlTools.ServiceLayer-win-x86-netcoreapp2.2.zip 

The error occurred because of an invalid Certificate File in the download path.

I downloaded the file manually and expanded the contents into the corresponding sub-directory based on the 1.4. layout. This allowed the extension to initialise and load.

When trying to use the Connect option on the taskbar at the bottom of screen however, the message ' You have No Profiles defined' (or similar??)  was displayed AND the create new connection icon at the top of the screen was greyed out.

Interestingly - if I use the keyboard shortcut CTRL_SHIFT_E  to try and execute the SQL code, my stored profiles appear in a dropdown at the top of the screen, and everything actually works as far as running a query goes.

This is all running in a Windows 7 Service Pack1  32-bit environment.

Extension version: 1.5.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:49:40.955Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2693)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|2.92GB (0.80GB free)|
|Process Argv|C:\Users\BunyNic\.vscode\extensions\ms-mssql.mssql-1.5.0\README.md|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kimera76** [comment] 2019-03-26 15:19
My team is having the same problem with the msssql 1.5.0 extension. Anyone that has updated to 1.5.0 is getting an error and is unusable.

![vscode_mssql_error](https://user-images.githubusercontent.com/4641177/55009400-78bcfa80-4fb0-11e9-958c-67d4cdfde8fa.png)

**Comment by kimera76** [comment] 2019-03-26 18:57
@nickbunyan , I got mine to work by rolling back to mssql 1.4. In the Extensions:Marketplace, click on the gear next to the extension and select "Install Another Version...", then pick the version you want and restart. Not sure if it's necessary, but I set my config to not auto update my extensions.

![image](https://user-images.githubusercontent.com/4641177/55025297-add84580-4fce-11e9-9c27-5b32ed720035.png)

**Comment by kburtram** [comment] 2019-03-26 19:55
This looks like an issue related to having a HTTPS inspection proxy which is incompatible with the Node.JS request module.  Though I'm surprised that 1.4 is working and 1.5 isn't since I don't think that component has changed between the two versions.  

The previous version was downloading from the Microsoft Download Center rather than GitHub, which may have been "whitelisted" by the HTTPS inspector, or some other environment configuration that was allowing this to work previously.  I'll take a look.

Note, IntelliSense is broken on 1.4 (which is the main reason we pushed 1.5 at this time).  Though if it's installing correctly then that is the best workaround until we can root cause the issue.

**Comment by kburtram** [comment] 2019-03-27 00:30
@nickbunyan @kimera76 I posted a VSIX that contains the changes in PR #1204 at https://azuredatastudiobuilds.blob.core.windows.net/test/vscode-mssql/mssql-1.5.1-sysca.vsix.

If possible, it would be helpful to see if this resolves the issue in the repro environment.  Please let me know if you're able to download this file, use the "Install from VSIX" command to side-load the extension, and if you still encounter the issue downloading the tools service with this build.  Thanks!

**Comment by nickbunyan** [comment] 2019-03-27 03:17
Regrettably I am travelling and will not be back on my Machine until Monday to test.

I can confirm that reverting to 1.4 using the install other version option does work as far as installing/connecting goes. Have not checked on intellisense functionality.

**Comment by kburtram** [comment] 2019-03-27 03:48
@nickbunyan thanks for the update.  Please let me know if you have a chance to validate later.  I'll leave the issue open until we're able to merge a fix since I think the issue may impact other users as well.

**Comment by kimera76** [comment] 2019-03-27 22:46
@kburtram I downloaded the VISX and installed as you described. I still get the same error as my screenshot above.

**Comment by kimera76** [comment] 2019-03-27 22:52
Well, I was able to get the VISX installed by unchecking the Proxy Strict SSL setting. I'm not sure that's the desired resolution.
![image](https://user-images.githubusercontent.com/4641177/55117511-21568180-50b9-11e9-980d-eb552a6470b3.png)

**Comment by kburtram** [comment] 2019-03-27 23:12
@kimera76 that's for trying out the test extension.  Turning off SSL certificate validation isn't a desirable fix, though it's good to know that solves the problem (it indicates the issue is correctly understood).  

I'll try to figure out why the proposed fix isn't working.  Do you happen to know if your proxy server certificate is in the Windows Certificate Store?

**Comment by kimera76** [comment] 2019-03-28 21:50
I had to ask a few people, but the answer I got was that our root cert is loaded in the local client store and is the root cert for our proxy server

**Comment by kburtram** [comment] 2019-03-29 19:44
@kimera76 thanks for the additional information.  I'll see if I can create a local repro environment.

**Comment by gontadu** [comment] 2019-04-16 10:17
In my case I have tried without a proxy and the tools download still fails after starting. More or less gets to about 5% and then terminates. Would this be a different issue?

**Comment by abist** [comment] 2019-11-08 22:58
@nickbunyan I'm going to go ahead and close this issue. Feel free to reopen this issue if you still see this issue persist in the latest version (1.7) of the extension.

**Closed by abist** 2019-11-08 22:58 UTC
Labels: bug
