### ISSUE TITLE
unsuported mysql syntax

### ISSUE THREAD

**Issue by hanjoosten** [Microsoft/vscode-mssql#1127] opened 2018-07-29 11:29 UTC
- MSSQL Extension Version: 
1.4.0
- VSCode Version:
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

The following statement is accepted in mysql, however, there are syntax errors found by the extension:

CREATE TABLE "Role"
     ( "Role" VARCHAR(255) UNIQUE NOT NULL /* OBJECT */
     , PRIMARY KEY ("Role")
     , "ts_insertupdate" TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
     ) ENGINE     = InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_BIN
     , ROW_FORMAT = DYNAMIC
;

![image](https://user-images.githubusercontent.com/1159672/43365842-46026786-9333-11e8-990e-4758911ee317.png)

**Comment by MattIrv** [comment] 2018-08-24 23:35
@hanjoosten see https://github.com/Microsoft/vscode-mssql/issues/801 and https://github.com/Microsoft/vscode-mssql/issues/1060 for more discussion of this issue. Unfortunately the various kinds of SQL aren't compatible enough that we could make one extension that works for everything, so this extension is specific to Microsoft SQL Server's syntax. I'll close this issue as a duplicate of those ones. I'd recommend trying the suggestion in the first issue I linked to disable the error messages if you still want to use this extension while working with MySQL

**Closed by MattIrv** 2018-08-24 23:35 UTC
