### ISSUE TITLE
Plugin applies intellisense to every sql document

### ISSUE THREAD

**Issue by ericbrian** [microsoft/vscode-mssql#17780] opened 2023-08-27 21:58 UTC
Every sql file I open, Tsql intellisense is used to show errors and such. However, not all of my sql files are for Sqlserver. I switch it over to none for those documents. But the next time I open the document, it tries to use Tsql again.

**Comment by Charles-Gagnon** [comment] 2023-08-29 16:33
Just to confirm - you're talking about this quickpick?

![image](https://github.com/microsoft/vscode-mssql/assets/28519865/17264533-8ad7-4a4a-82c7-5f67216a5800)

(vs the "Language Mode" quickpick)

**Comment by kburtram** [comment] 2024-08-28 23:20
This looks like a duplicate of https://github.com/microsoft/vscode-mssql/issues/801

**Closed by kburtram** 2024-08-28 23:20 UTC
Labels: Enhancement, Area - Language Service
