### ISSUE TITLE
Issues with dbs having name of <default>

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#1427] opened 2019-10-14 22:21 UTC
In places such as https://github.com/microsoft/vscode-mssql/blob/f836c23ce4be6b0081ab75de453f49c582b4e7d2/src/controllers/mainController.ts#L167 we're just doing a hard-coded check against the label <default>. But if a db actually has that as its name then we aren't going to update the DB name correctly. 

1. User creates connection to server and specifies the database named <default> as the initial DB
2. User runs New Query on another DB under the connection
3. User runs New Query on the server node

Expected :

New Query is ran in the context of the database named <default>

Actual :

New Query is ran with the default DB for the user (master or whatever it's set to on the server)

Note that this is one example of where this is done incorrectly, there are likely other places too so an audit of all usages of the defaultDatabaseLabel var should be done to verify we aren't using this incorrectly anywhere else.

**Comment by kburtram** [comment] 2024-08-15 19:05
Closing older issues that aren't planned on our roadmap as "By Design".

**Closed by kburtram** 2024-08-15 19:05 UTC
Labels: Bug, Area - Connection
