### ISSUE TITLE
Failing to login

### ISSUE THREAD

**Issue by drorata** [Microsoft/vscode-mssql#824] opened 2017-04-20 09:13 UTC
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.11.12
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. First, installed openssl (using `macports`) and created the symlinks:
```
sudo ln -s /opt/local/lib/libcrypto.1.0.0.dylib /usr/local/lib/
sudo ln -s /opt/local/lib/libssl.1.0.0.dylib /usr/local/lib/
```
2. Next, I installed `dotnet-dev-osx-x64.1.0.1.pkg`
3. Installed the `mssql` extension
4. Started a new file and set its language to `sql`.
5. Started a new connection `SHIFT + CMD +C`
6. Provided server name: `hello-world.foo.bar`
7. Left database to connect empty
8. Provided username (I tried both with and without domain) and password

I got the following error:

```
mssql: Error 18456: Login failed for user 'user.name'.
RetryClose
Errormssql: Error: Unable to connect using the connection information provided. Retry profile creation?
```

Note that I could connect using `SQLPro for MSSQ` and `sqlEctron` from the same machine.

**Comment by kevcunnane** [comment] 2017-04-21 17:18
@drorata just confirming - this is a SQL username and password rather than a domain login? At present we only support SQL Authentication on Mac and Linux. If so, is the repro to use `user.name` as the login? I'm wondering if non-`.` usernames work.

**Comment by drorata** [comment] 2017-04-24 06:50
@kevcunnane When setting the connection I provide the URL to the database. As a username I provide: `DOMAIN\user.name` where `DOMAIN` is the domain and `user.name` is my username which includes a `.` (dot).

If I understand correctly, this means I need the `Windows authentication` which is not supported. Is that correct?

**Comment by kevcunnane** [comment] 2017-04-24 23:06
Correct, you need Windows Authentication. This is supported on Windows but not Mac/Linux yet. This feature is high on our backlog (expected in the next 1-2 months) but requires us to update everything to .Net Core 2.0, which isn't officially released yet. Hence the delay. 

I am going to close this as a duplicate of #356 as that's our main tracking item for that work.

**Closed by kevcunnane** 2017-04-24 23:06 UTC
Labels: customer issue
