### ISSUE TITLE
Cannot start SQL Statement with mssql.runCurrentStatement

### ISSUE THREAD

**Issue by pwahlmueller** [microsoft/vscode-mssql#1603] opened 2020-02-25 17:01 UTC
- MSSQL Extension Version: 1.8.0
- VSCode Version: 1.42.1
- OS Version: Microsoft Windows 10.0.18362

If I want to run the statement below with hitting the key assigned to mssql.runCurrentStatement it will not run properly, wheter you select the whole command or not.
It works using mssql.runquery or the enterprise manager.

```sql
DECLARE
  @basedate DATETIME,
  @offset   INT
SELECT
    @basedate = '2017-01-01',
    @offset = 1

WHILE (@offset < 2020)
BEGIN
    INSERT INTO CalendarMonth ([anydate])
    values (DATEADD(day, @offset, @basedate))
    SELECT @offset = @offset + 1
END
```

**Steps to Reproduce**

1. Create table
2. Create Keyboard Shortcut to mssql.runCurrentStatement
3. Try to execute statement above with Shortcut tun mssql.runCurrentStatement

**Result**
Selecting the whole command does nothing
![grafik](https://user-images.githubusercontent.com/8706955/75268780-42a77c80-57f8-11ea-85ff-c2c87e06a798.png)

Not selecting anything results in an error (this one could be tricky)
![grafik](https://user-images.githubusercontent.com/8706955/75269219-da0ccf80-57f8-11ea-8992-0ae1fbba5591.png)

**Some code to reproduce**
SQL to create table used for statement above
```sql
CREATE TABLE CalendarMonth
(
    anydate DATETIME,
    PRIMARY KEY (anydate)
)
```
Keyboard Shortcut used in my case
```json
{
     "key": "f8",
     "command": "mssql.runCurrentStatement",
     "when": "editorTextFocus && editorLangId == 'sql'"
}
```

**Comment by abist** [comment] 2020-02-26 01:49
@pwahlmueller Thanks for opening this issue. This is an interesting case because the engine thinks the `DECLARE` statement as one batch, and just executes that. Will look into this issue for better batch parsing.

**Comment by kburtram** [comment] 2024-08-15 19:28
Closing this as "By Design" as the DECLARE statement is treated as a standalone statement (which seems correct according to SQL language definition).  If the DECLARE and the SELECT statements are highlighted then the command correctly executes both statements on the current extension version.

**Closed by kburtram** 2024-08-15 19:28 UTC
Labels: Bug, Area - Query Editor
