### ISSUE TITLE
Command 'mssql.editConnection' Not Found

### ISSUE THREAD

**Issue by tmng8888** [microsoft/vscode-mssql#17989] opened 2024-08-23 14:17 UTC
- MSSQL Extension Version: 1.23.0
- VSCode Version: 1.92.2
- OS Version: Windows 11 Home, 23H2

Steps to Reproduce:

1. When I click the pencil icon to edit a connection, I get the error:
_Error running command mssql.editConnection: command 'mssql.editConnection' not found. This is likely caused by the extension that contributes mssql.editConnection._

2. The workaround now is to edit settings.json file.

**Comment by kburtram** [comment] 2024-08-23 15:54
@tmng8888 is the extension working otherwise and crashing/failing only when you try to edit a connection?  If so, it there anything noteworthy regarding the connection details that would help to repro the issue?

**Comment by tmng8888** [comment] 2024-08-23 17:50
Only this error message appeared after clicking **Edit Connection** (pencil icon)
![image](https://github.com/user-attachments/assets/ecd2e8bf-87fd-4a32-9049-5784922a3ae9)

I suppose this is graceful message by VSCode as it could fine the _mssql.editConnection_ command in the extension.

**Comment by kburtram** [comment] 2024-08-26 20:26
Do you know if there was any exception in the "Help->Toggle Developer Tools" Console?  Unfortunately, I'm unable to reproduce this and there aren't enough details in that error message to determine what's happening.  Typically, "command not found" errors indicate an error early in extension loading prior to command registration, but I'd need to know the specific error to try to provide assistance.

**Comment by kburtram** [comment] 2024-08-26 21:47
@tmng8888 sorry for the confusion, the Edit Connection feature is only available if you have the following setting `"mssql.enableExperimentalFeatures": true`.  You would need to manually edit the User Settings JSON to enable with the 1.23.0 release.  

We are working on a GUI-based connection experience but it is in early development and not ready for general usage.  The Edit Connection button shouldn't be visible without this setting enabled.

@aasimkhan30 could you please confirm the Edit Connection button is hidden when experimental features are disabled for 1.24.0 release?

**Comment by kburtram** [comment] 2024-08-27 23:49
I confirmed the Edit Connection command is gone for connections without the experimental features flag with the 1.24.0 internal build, which is planned for release next week.  Closing this as fixed based on that.  Please let us know if there's anything else for this issue.  Thanks for reporting!

**Closed by kburtram** 2024-08-27 23:49 UTC
Labels: Bug, Area - Connection
