### ISSUE TITLE
Support for importing .bacpac files

### ISSUE THREAD

**Issue by tinchou** [Microsoft/vscode-mssql#420] opened 2016-11-28 04:55 UTC
Hi,

I'd like to know if there are any plans to support importing a `.bacpac` file. I sometimes get database dumps from Azure in this format and I've always used SSMS to import them. It would be great to have this feature in this extension too.

Thanks!

**Comment by erickangMSFT** [comment] 2016-11-28 20:24
Database migration with Import and Export scenario is supported on SQL on all platforms including Windows, Linux and Azure SQL DB using sqlpackage.exe. For SQL on Linux, please see the tutorial on https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-migrate-sqlpackage. sqlpackage.exe is the recommended way for the database migration.

**Comment by borgdylan** [comment] 2016-12-19 06:40
Sqlpackage comes with SQL server itself in the Linux case. Unless it gets distributed with sqlcmd in the tools package it will be hard to take a dependency on.

**Comment by kevcunnane** [comment] 2017-05-16 23:44
I'm going to close this as out of scope for our extension. We've got a fairly clear scope for what this extension does, and this kind of scenario doesn't fit in it. We don't intend putting administration / backup / migration features into this VSCode extension.

**Closed by kevcunnane** 2017-05-16 23:44 UTC
Labels: backlog, customer issue, suggestion

**Comment by NixonInnes** [comment] 2025-02-11 10:48
With Azure Data Studio being retired; is there now plans to include the Data-Tier functionality into the VS Code extension?

**Comment by domenichelfenstein** [comment] 2025-02-12 07:57
@NixonInnes 
I had the exact same question in mind.
Personally, I'm not able to migrate from Azure Data Studio to the VS Code MSSQL extension as long as I can't import bacpacs and delete databases on my server.

Thanks for reconsidering the feature.

**Comment by ctolkien** [comment] 2025-02-13 07:15
I'm also here with the same scenario. Can we get this reopened?

**Comment by ctolkien** [comment] 2025-02-13 07:16
Now a dupe of https://github.com/microsoft/vscode-mssql/issues/18644
