### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by pmbdlw** [microsoft/vscode-mssql#17093] opened 2021-11-08 12:08 UTC
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.10.1`
- OS Version: `Windows_NT x64 10.0.22494`
- VS Code version: `1.62.0`

:warning: We have written the needed data into your clipboard. Please paste! :
warning:{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 15954,
		"activateCallTime": 3,
		"activateResolvedTime": 19033,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-mssql.data-workspace-vscode",
				"_lower": "ms-mssql.data-workspace-vscode"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}

**Comment by pmbdlw** [comment] 2021-11-08 12:09
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 15954,
		"activateCallTime": 3,
		"activateResolvedTime": 19033,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-mssql.data-workspace-vscode",
				"_lower": "ms-mssql.data-workspace-vscode"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by Charles-Gagnon** [comment] 2021-11-08 16:59
Closing as a duplicate of https://github.com/microsoft/vscode-mssql/issues/17087 - could you respond in that issue with information about the workspace/folder you have opened (if any)? I'm commenting in that issue with the specific things we're looking for.

**Closed by Charles-Gagnon** 2021-11-08 16:59 UTC
